### ISSUE TITLE
Won't Delete After after Running Windows 10 Debloat Scripts

### ISSUE THREAD

**Issue by CyberPunkInterface** [bleachbit/bleachbit#1064]
**BleachBit Won't Delete Windows Explorer List**
After running Windows 10 Debloat scripts BleachBit Won't delete/clean Windows Explorer List.
-Most recently used
-Recent documents list
-Run
-Search history
-Shellbags
-Thumbnails

This happened ever since I have ran The Windows 10 De bloat Scripts, certain Windows things mainly the Windows explorer list wont get deleted/cleaned. I don't think I had BleachBit installed before running the Debloat Scripts. I have had BleachBit installed on other Windows 10 setups and installs and it never had this issue, also never have run Debloat Scripts on those installs. Therefore I don't know if having Bleachbit installed before running The Debloat Scripts would fix this issue or how to fix this issue but I do believe Bleachbit is not recognizing certain windows files due to running the Scripts. I reinstalled BleachBit but it didn't solve this issue. Any help or anyone else have this issue and how to fix it.
Thanks.   

 - OS: Windows 10
 - BleachBit version 4.0.0

**Comment by az0** [comment]
> **BleachBit Won't Delete Windows Explorer List**
> After running Windows 10 Debloat scripts 

Do you mean https://christitus.com/debloat-windows-10-2020/ or https://github.com/Sycnex/Windows10Debloater or something else?

**Comment by CyberPunkInterface** [comment]
> > Do you mean https://christitus.com/debloat-windows-10-2020/ or https://github.com/Sycnex/Windows10Debloater or something else?

Its this one https://github.com/farag2/Windows-10-Sophia-Script that I used. 

technically It is one on the  https://christitus.com/debloat-windows-10-2020/ page under Other GitHub Projects for Debloating Windows section.

**Comment by az0** [comment]
> **BleachBit Won't Delete Windows Explorer List**
> After running Windows 10 Debloat scripts BleachBit Won't delete/clean Windows Explorer List.
>I do believe Bleachbit is not recognizing certain windows files due to running the Scripts. 
>I reinstalled BleachBit but it didn't solve this issue.

Tell me more about the malfunction. For example, does BleachBit give an error message? If so, what is is exactly? Or do you mean BleachBit finishes without an error, but the traces of Windows Explorer lists are left behind?

**Comment by CyberPunkInterface** [comment]
Yes BleachBit gives an error message. It says 544 errors. The List is long  don't think I want to post the whole thing, but most of it looks like this:


> > Error: winapp2_windows.windows_error_reporting_extras: Command to delete C:\ProgramData\Microsoft\Windows\WER\Temp\.lock
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 82, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 350, in delete
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 789, in wipe_contents
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 926, in file_wipe
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 435, in open_file
pywintypes.error: (5, 'CreateFileW', 'Access is denied.')
Error: winapp2_windows.windows_logs: Command to delete C:\ProgramData\Microsoft\Network\Downloader\qmgr.db
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 82, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 350, in delete
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 789, in wipe_contents
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 953, in file_wipe
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 714, in poll_clusters_freed
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 326, in check_extents
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 402, in check_mapped_bit
TypeError: ord() expected string of length 1, but int found
Error: winapp2_windows.windows_logs: Command to delete C:\ProgramData\USOShared\Logs\System\MoUsoCoreWorker.002339f0-a578-4fa6-bc68-fcdad130e03e.1.etl
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 82, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 350, in delete
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 789, in wipe_contents
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 926, in file_wipe
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 435, in open_file
pywintypes.error: (5, 'CreateFileW', 'Access is denied.')
Error: winapp2_windows.windows_logs: Command to delete C:\ProgramData\USOShared\Logs\System\MoUsoCoreWorker.002d09ed-20b7-447b-949b-46f190211aef.1.etl
> 
> 
> 
>

**Comment by az0** [comment]
[BleachBit 4.2.0 ](https://www.bleachbit.org/news/bleachbit-420)has a fix for this "access is denied" error in WindowsWipe.py. Please upgrade, try again, and let me know how it goes.

**Comment by CyberPunkInterface** [comment]
Have updated to 4.2.0 and Now BleachBit finishes without an error, but the traces of Windows Explorer lists are left behind. How do I fix this? 

Do I need to install BleachBit Before running Debloat Scripts or Change/Modify the Debloat Scripts to fix this for New Fresh Windows10 Installs?

**Comment by az0** [comment]
> Have updated to 4.2.0 and Now BleachBit finishes without an error

Great to hear, so I would like to close the issue.

> but the traces of Windows Explorer lists are left behind. How do I fix this?

Please open a new issue, and please be specific as to what the traces are, so I can reproduce the problem. Maybe a screenshot would help. 

> Do I need to install BleachBit Before running Debloat Scripts or Change/Modify the Debloat Scripts to fix this for New Fresh Windows10 Installs?

I'm not familiar with the scripts, so maybe the authors of the scripts can offer better support. My guess is it may not matter, but I am not sure.
