### ISSUE TITLE
Error generating chaff decoy

### ISSUE THREAD

**Issue by useribs** [bleachbit/bleachbit#1066]
**Error message when trying to make chaff with following options**
![image](https://user-images.githubusercontent.com/16052461/102021974-cf75f380-3d94-11eb-8198-755d3ca19e6a.png)

Steps: make config, error appears after pressing OK to download "chaff data" thingie. Changing destination folder options, delete/do not delete options etc does not affect the error.

`
Traceback (most recent call last):
  File "bleachbit\GuiChaff.pyo", line 158, in on_make_files
  File "bleachbit\GuiChaff.pyo", line 138, in download_models_dialog
  File "bleachbit\GuiChaff.pyo", line 128, in download_models_gui
  File "bleachbit\Chaff.pyo", line 259, in download_models
  File "bleachbit\Chaff.pyo", line 192, in download_url_to_fn
  File "requests\__init__.pyo", line 43, in <module>
  File "urllib3\__init__.pyo", line 8, in <module>
  File "urllib3\connectionpool.pyo", line 28, in <module>
  File "urllib3\packages\six.pyo", line 92, in __get__
  File "urllib3\packages\six.pyo", line 115, in _resolve
  File "urllib3\packages\six.pyo", line 82, in _import_module`

BleachBit version 4.1.1
Build number 1770
GTK version 3.18.9

platform.win32_ver[1]() = 6.3.9600
platform.platform = Windows-8.1-6.3.9600
platform.version = 6.3.9600
sys.argv = ['C:\\tools\\BleachBit-Portable\\bleachbit.exe', '--gui', '--no-uac']
sys.executable = C:\tools\BleachBit-Portable\bleachbit.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]

![image](https://user-images.githubusercontent.com/16052461/102022105-a30ea700-3d95-11eb-80e2-8376691b54bb.png)

**Comment by az0** [comment]
Based on initial evaluation, this is good detail for a bug report, and the problem looks like an error related to setting up the downloading process.

@useribs 
Which antivirus/security software is on this system?

**Comment by useribs** [comment]
None

**Comment by az0** [comment]
You can download the release here: [BleachBit 4.2.0 (final)](https://www.bleachbit.org/news/bleachbit-420)

@mkhon  Thank you! :)
