### ISSUE TITLE
Exception on FreeBSD

### ISSUE THREAD

**Issue by Carmina16** [bleachbit/bleachbit#1117]
https://github.com/bleachbit/bleachbit/blob/b630c7c055abf2126fe01e57aa631b4b8f58f666/bleachbit/Unix.py#L503-L507

Is this a MacOS code? In FreeBSD, `subprocess` returns a bytestring, and `re` cannot parse it. Probably a decoding step should be added somewhere?

**Comment by abitrolly** [comment]
@Carmina16 that looks like Python 2 code. Can you post the full trace to see the exception and if there was custom `run_ps()` passed?

**Comment by Carmina16** [comment]
```
Exception while running operation 'chromium': 'a bytes-like object is required, not 'str''
Traceback (most recent call last):
  File "/usr/home/user/bleachbit-4.2.0/bleachbit/Worker.py", line 346, in run_operations
    for dummy in self.clean_operation(operation):
  File "/usr/home/user/bleachbit-4.2.0/bleachbit/Worker.py", line 144, in clean_operation
    if self.really_delete and backends[operation].is_running():
  File "/usr/home/user/bleachbit-4.2.0/bleachbit/Cleaner.py", line 162, in is_running
    if Unix.is_running(pathname):
  File "/usr/home/user/bleachbit-4.2.0/bleachbit/Unix.py", line 541, in is_running
    return is_running_darwin(exename)
  File "/usr/home/user/bleachbit-4.2.0/bleachbit/Unix.py", line 507, in is_running_darwin
    for p in run_ps().split("\n") if p != "")
TypeError: a bytes-like object is required, not 'str'
```

**Comment by az0** [comment]
> Is this a MacOS code?

Yes, `is_running_darwin()` is for MacOS

**Comment by Carmina16** [comment]
Does it actually work (without exceptions)?

**Comment by abitrolly** [comment]
@Carmina16 can you check that the PR #1291 works properly?
