### ISSUE TITLE
`[WinError 5] Access is denied` when cleaning Windows Defender - Backup Files

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#1125]
User has **admin privileges**, and **overwriting files** is enabled.

Diagnostics window (excerpt)
```
BleachBit version 4.2.0
Build number 1829
platform.platform = Windows-10-10.0.19041
win32com.shell.shell.IsUserAnAdmin() = True
```

Application log
```
[WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpasbase.vdm

Error: windows_defender.backup: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpasdlta.vdm
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 82, in execute
  File "bleachbit\FileUtilities.pyo", line 350, in delete
  File "bleachbit\FileUtilities.pyo", line 790, in wipe_contents
  File "bleachbit\WindowsWipe.pyo", line 931, in file_wipe
  File "bleachbit\WindowsWipe.pyo", line 435, in open_file
pywintypes.error: (5, 'CreateFileW', 'Access is denied.')



[WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpavbase.vdm

Error: windows_defender.backup: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpavdlta.vdm
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 82, in execute
  File "bleachbit\FileUtilities.pyo", line 350, in delete
  File "bleachbit\FileUtilities.pyo", line 790, in wipe_contents
  File "bleachbit\WindowsWipe.pyo", line 931, in file_wipe
  File "bleachbit\WindowsWipe.pyo", line 435, in open_file
pywintypes.error: (5, 'CreateFileW', 'Access is denied.')

Error: windows_defender.backup: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpengine.dll
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 82, in execute
  File "bleachbit\FileUtilities.pyo", line 350, in delete
  File "bleachbit\FileUtilities.pyo", line 790, in wipe_contents
  File "bleachbit\WindowsWipe.pyo", line 931, in file_wipe
  File "bleachbit\WindowsWipe.pyo", line 435, in open_file
pywintypes.error: (5, 'CreateFileW', 'Access is denied.')

Error: windows_defender.backup: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpengine.lkg
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 82, in execute
  File "bleachbit\FileUtilities.pyo", line 350, in delete
  File "bleachbit\FileUtilities.pyo", line 790, in wipe_contents
  File "bleachbit\WindowsWipe.pyo", line 931, in file_wipe
  File "bleachbit\WindowsWipe.pyo", line 435, in open_file
pywintypes.error: (5, 'CreateFileW', 'Access is denied.')


Disk space recovered: 0
Files deleted: 0
Errors: 6
```

Expected behavior: if file cannot be deleted now, mark it for deletion at reboot.

Ideally, we would have a unit test for this case.

**Comment by Marvin0401** [comment]
Hi @az0 , Can I work on this issue?

**Comment by az0** [comment]
Like https://github.com/bleachbit/bleachbit/issues/1004 except my traceback shows that overwriting was enabled

**Comment by Andrew-J-Larson** [comment]
P.s. ran into this issue today. If Defender has tamper protection on (which is usually going to be the case by default), access will always be denied.

You would have to either temporarily disable tamper protection, or avoid turning on the Defender based cleanups.

**Comment by rados** [comment]
Just tried to disable the tamper protection with this PS command, but it didn't work:

Set-MpPreference -DisableTamperProtection $true

**Comment by Andrew-J-Larson** [comment]
> Just tried to disable the tamper protection with this PS command, but it didn't work:
> 
> Set-MpPreference -DisableTamperProtection $true

Tamper protection is only the first step, after that, you would need to temporarily change permissions on the defender folder to allow your user account to modify/delete/etc.

That part is the chore, which is why I just recommend having the defender option just turned off in general.

**Comment by Andrew-J-Larson** [comment]
As an alternative, if you really want to clean Defender files, just use "Disk Cleanup" ran as admin, and make sure "Microsoft Defender Antivirus" is checked.

**Comment by Andrew-J-Larson** [comment]
However, if @az0 wants to look at using `CleanMgr.exe`, then won't even have to worry about these permission errors (but won't have precise control over knowing what, if anything is removed:
- https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cleanmgr
- https://learn.microsoft.com/en-us/troubleshoot/windows-server/backup-and-storage/automating-disk-cleanup-tool#registry-key-information

More research would be needed to see how to properly automate `CleanMgr.exe` to just clean Defender files.

**Comment by az0** [comment]
[This change simplifies the error message](https://github.com/bleachbit/bleachbit/commit/d6951006bfa81941f4c1a7e321d5f5a625013f22) for access denied to a single line.
