### ISSUE TITLE
FAIL: test_system_recent_documents (tests.TestCleaner.CleanerTestCase)

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#1158]
https://ci.appveyor.com/project/az0/bleachbit/builds/39070526#L2279

======================================================================
FAIL: test_system_recent_documents (tests.TestCleaner.CleanerTestCase)
Clean recent documents in GTK
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestCleaner.py", line 217, in test_system_recent_documents
    self.assertTrue(mgr.has_item(uri))
AssertionError: False is not true
----------------------------------------------------------------------

**Comment by abitrolly** [comment]
More errors on Travis.

```
======================================================================

ERROR: test_no_files_exist (tests.TestCleaner.CleanerTestCase)

Verify only existing files are returned

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/bleachbit/bleachbit/tests/TestCleaner.py", line 187, in test_no_files_exist

    for cmd in backends[key].get_commands(option_id):

  File "/home/travis/build/bleachbit/bleachbit/bleachbit/Cleaner.py", line 482, in get_commands

    '~/snap/*/*/.local/share/recently-used.xbel'))

  File "/opt/python/3.7.6/lib/python3.7/glob.py", line 20, in glob

    return list(iglob(pathname, recursive=recursive))

TypeError: <lambda>() got an unexpected keyword argument 'recursive'
```
 And the comparison with the latest good commit https://github.com/bleachbit/bleachbit/compare/d8c33f873845de00dd50033d60509fe0bacd73b0...master
https://travis-ci.com/github/bleachbit/bleachbit/jobs/503988794#L712

**Comment by rados** [comment]
@az0 
I am interested to fix this one.
