### ISSUE TITLE
unit test failures for ini on Travis CI

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#1301]
```

FAIL: test_ini (tests.TestAction.ActionTestCase)
Unit test for class Ini
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bleachbit/bleachbit/tests/TestAction.py", line 245, in test_ini
    test_ini_helper(self, execute_ini)
  File "/home/travis/build/bleachbit/bleachbit/tests/TestFileUtilities.py", line 61, in test_ini_helper
    self.assertEqual(14, os.path.getsize(filename))
AssertionError: 14 != 17

FAIL: test_clean_ini (tests.TestFileUtilities.FileUtilitiesTestCase)
Unit test for clean_ini()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bleachbit/bleachbit/tests/TestFileUtilities.py", line 212, in test_clean_ini
    test_ini_helper(self, clean_ini)
  File "/home/travis/build/bleachbit/bleachbit/tests/TestFileUtilities.py", line 61, in test_ini_helper
    self.assertEqual(14, os.path.getsize(filename))
AssertionError: 14 != 17
```

**Comment by abitrolly** [comment]
Fixed by #1303.

Travis CI is not building anything since May - https://app.travis-ci.com/github/bleachbit/bleachbit/builds

Looks like time to switch to GitHub Actions. Or maybe https://github.com/bleachbit/bleachbit/issues/1171
