### ISSUE TITLE
FAIL: test_detect_encoding (tests.TestFileUtilities.FileUtilitiesTestCase)

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#1302]
```
FAIL: test_detect_encoding (tests.TestFileUtilities.FileUtilitiesTestCase)
Unit test for detect_encoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/bleachbit/bleachbit/tests/TestFileUtilities.py", line 483, in test_detect_encoding
    self.assertEqual(det, expected_encoding)
AssertionError: None != 'ascii'
```

https://app.travis-ci.com/github/bleachbit/bleachbit/jobs/548004870#L1148

**Comment by abitrolly** [comment]
Repeatable on my machine.
```
$ python -m unittest tests/TestFileUtilities.py -k test_detect_encoding -v
/tmp/FileUtilitiesTestCaseh126fphu
test_detect_encoding (tests.TestFileUtilities.FileUtilitiesTestCase)
Unit test for detect_encoding ... chardet module is not available to detect character encoding
FAIL

======================================================================
FAIL: test_detect_encoding (tests.TestFileUtilities.FileUtilitiesTestCase)
Unit test for detect_encoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anatoli/src/bleachbit/tests/TestFileUtilities.py", line 483, in test_detect_encoding
    self.assertEqual(det, expected_encoding)
AssertionError: None != 'ascii'

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)                                
```

**Comment by abitrolly** [comment]
This fixed the problem.
```
pip install chardet
```
