### ISSUE TITLE
Bleachbit (normal) crashes on Ubuntu 20.04

### ISSUE THREAD

**Issue by Razorsedge90** [bleachbit/bleachbit#1305]
**Bug**
Whereas Bleachbit(root) is ok, Bleachbit(normal) crashes with line 

File "/usr/lib/python3.8/configparser.py", line 1163, in _convert_to_boolean
     raise ValueError('Not a boolean: %s' % value)
 ValueError: Not a boolean: ['False']

**To Reproduce**
1. Download and install: bleachbit_4.4.2-0_all_ubuntu2004.deb
2. Click on Bleachbit (not root)
3. Error

**Error Message (from /var/crashes/**
Traceback:
 Traceback (most recent call last):
   File "/usr/bin/bleachbit", line 43, in <module>
     import bleachbit.GUI
   File "/usr/share/bleachbit/GUI.py", line 26, in <module>
     from bleachbit import Cleaner, FileUtilities
   File "/usr/share/bleachbit/Cleaner.py", line 32, in <module>
     from bleachbit.Options import options
   File "/usr/share/bleachbit/Options.py", line 381, in <module>
     set_root_log_level()
   File "/usr/share/bleachbit/Log.py", line 83, in set_root_log_level
     is_debug = options.get('debug')
   File "/usr/share/bleachbit/Options.py", line 163, in get
     return self.config.getboolean(section, option)
   File "/usr/lib/python3.8/configparser.py", line 828, in getboolean
     return self._get_conv(section, option, self._convert_to_boolean,
   File "/usr/lib/python3.8/configparser.py", line 808, in _get_conv
     return self._get(section, conv, option, raw=raw, vars=vars,
   File "/usr/lib/python3.8/configparser.py", line 803, in _get
     return conv(self.get(section, option, **kwargs))
   File "/usr/lib/python3.8/configparser.py", line 1163, in _convert_to_boolean
     raise ValueError('Not a boolean: %s' % value)
 ValueError: Not a boolean: ['False']

**Desktop**
 - OS: Ubuntu 20.04.03
 - BleachBit version [4.4.2] (however on 4.4.0 same error)

**Additional context**
I use python from anaconda.

**Comment by abitrolly** [comment]
I expect there is an error in non-root config file. Even if so, the error message could be better. Can you provide the config that BleachBit is reading?
