### ISSUE TITLE
What title?

### ISSUE THREAD

**Issue by KravenTruth** [bleachbit/bleachbit#1380]
[BleachBit.log](https://github.com/bleachbit/bleachbit/files/9264145/BleachBit.log)
This is what I found when Bleachbit failed to work.  Input please... Attachment is log file...
Thnx

**Comment by az0** [comment]
Which antivirus or security software to use?

**Comment by KravenTruth** [comment]
The AV I use is Gridinsoft.


     On Thursday, August 4, 2022, 06:21:45 PM MDT, Andrew Ziem ***@***.***> wrote:  
 
 

Which antivirus or security software to use?

**Comment by az0** [comment]
Interesting. I never heard of Gridinsoft.

1. Did you download BleachBit from the official web site www.bleachbit.org ?
2. When you installed and start BleachBit, does it have an intact digital security certificate with the name Andrew Ziem? (For example, see [installation docs](https://docs.bleachbit.org/doc/install-on-windows.html).)
3. Only if yes to both questions, consider temporarily pausing or disabling the Gridinsoft system to check whether this prevents the error. 

I am wondering whether there is a false positive from the virus scanner. This happens from time to time.

To make it easier to read, this is the attached log

```
Traceback (most recent call last):
  File "bleachbit.py", line 37, in <module>
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: Operation did not complete successfully because the file contains a virus or potentially unwanted software.) 'C:\\Program Files (x86)\\BleachBit\\win32api.pyd'
```

**Comment by abitrolly** [comment]
https://www.virustotal.com/gui/file/3cc1fb7edf92e90330e833b1abe6148762aea61b6d712aa1c764018dd8c70e32 the portable version triggers this GridinSoft. Installer is ok, probably because this tool doesn't know how to unpack them.

**Comment by az0** [comment]
I am closing this ticket:
- I haven't heard from KravenTruth.
- This ticket was apparently for BleachBit-4.4.2-portable.zip, which is now very old. 
- VirusTotal reports no detections by Gridinsoft for BleachBit version 5.1.0.
- BleachBit 5.1.0 has several changes "under the hood" that prevent or change how antivirus handles it.

If you have the "DLL load failed" or virus false positives in a newer version, please open a new ticket.
