### ISSUE TITLE
"DLL load failed while importing _psutil_windows" in mkhon-python310 branch

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#1428]
```
======================================================================
ERROR: test_free_space (tests.TestFileUtilities.FileUtilitiesTestCase)
Unit test for free_space()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestFileUtilities.py", line 546, in test_free_space
    result = free_space(home)
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 523, in free_space
    import psutil
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ImportError: DLL load failed while importing _psutil_windows: The specified module could not be found.
======================================================================
ERROR: test_guess_overwrite_paths (tests.TestFileUtilities.FileUtilitiesTestCase)
Unit test for guess_overwrite_paths()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestFileUtilities.py", line 660, in test_guess_overwrite_paths
    for path in guess_overwrite_paths():
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 598, in guess_overwrite_paths
    if localtmp and same_partition(localtmp, drive):
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 673, in same_partition
    return free_space(dir1) == free_space(dir2)
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 523, in free_space
    import psutil
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ImportError: DLL load failed while importing _psutil_windows: The specified module could not be found.
======================================================================
ERROR: test_same_partition (tests.TestFileUtilities.FileUtilitiesTestCase)
Unit test for same_partition()
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestFileUtilities.py", line 713, in test_same_partition
    self.assertTrue(same_partition(home, home))
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 673, in same_partition
    return free_space(dir1) == free_space(dir2)
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 523, in free_space
    import psutil
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ImportError: DLL load failed while importing _psutil_windows: The specified module could not be found.
======================================================================
ERROR: test_wipe_path_fast (tests.TestFileUtilities.FileUtilitiesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestFileUtilities.py", line 942, in test_wipe_path_fast
    next(wipe_path(self.tempdir, True))
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 933, in wipe_path
    start_free_bytes = free_space(pathname)
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 523, in free_space
    import psutil
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ImportError: DLL load failed while importing _psutil_windows: The specified module could not be found.
======================================================================
ERROR: test_is_process_running (tests.TestWindows.WindowsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestWindows.py", line 458, in test_is_process_running
    is_process_running(test[1]),
  File "C:\projects\bleachbit\bleachbit\Windows.py", line 492, in is_process_running
    import psutil
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\__init__.py", line 109, in <module>
    from . import _pswindows as _psplatform
  File "C:\projects\bleachbit\x86-windows\tools\python3\lib\site-packages\psutil\_pswindows.py", line 35, in <module>
    from ._psutil_windows import ABOVE_NORMAL_PRIORITY_CLASS
ImportError: DLL load failed while importing _psutil_windows: The specified module could not be found.
======================================================================
```

full log: https://ci.appveyor.com/project/az0/bleachbit/builds/45438017

**Comment by mkhon** [comment]
This should be fixed in this PR: https://github.com/bleachbit/bleachbit/pull/1439
Before running unit tests you need to run windows\python-gtk3-fixup.bat

**Comment by az0** [comment]
This error is gone from [build log for 2310](https://ci.appveyor.com/project/az0/bleachbit/builds/45819846?fullLog=true). Thank you, @mkhon
