### ISSUE TITLE
AttributeError when shredding files from clipboard

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#1445]
# To reproduce

1. In Windows Explorer, copy files to clipboard
2. In BleachBit application, press CTRL+V

_Or_ 

1. In Windows Explorer, copy files to clipboard
2. In BleachBit application, click application menu
3. Click *Shred Paths from Clipboard*

# What happens

Error is printed to console, but no files are previewed or deleted.

```
Traceback (most recent call last):
  File "bleachbit\GUI.pyc", line 241, in cb_clipboard_uri_received
AttributeError: 'NoneType' object has no attribute 'get_uris'
```

# System

- Build 2310 (new Python 3.10 and GTK 2.24)
- Windows 10

**Comment by az0** [comment]
@mkhon 
Please take a look

**Comment by az0** [comment]
Basically same now

```
Traceback (most recent call last):
  File "bleachbit\GUI.pyc", line 237, in cb_clipboard_uri_received
AttributeError: 'NoneType' object has no attribute 'get_uris'
```
