### ISSUE TITLE
Don't make free space. HD full. Not excessible

### ISSUE THREAD

**Issue by rockdaddy1956** [bleachbit/bleachbit#1472]
Don't make free space. HD full. Not excessible

Error happens:
Fout: system.free_disk_space: Function: Overschrijf de vrije schijfruimte op D:\
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 145, in execute
  File "bleachbit\Cleaner.pyo", line 561, in wipe_path_func
  File "bleachbit\FileUtilities.pyo", line 1013, in wipe_path
KeyError: 'files '

Registersleutel verwijderen 0B HKCU\Software\Microsoft\Internet Explorer\TabbedBrowsing\NewTabPage
Registersleutel verwijderen 0B HKCU\Software\Microsoft\Internet Explorer\Main\FeatureControl
Registersleutel verwijderen 0B HKCU\Software\Microsoft\Internet Explorer\Recovery\PendingDelete
Registersleutel verwijderen 0B HKCU\Software\Microsoft\Windows\CurrentVersion\Ext\Stats
Verwijderen 0B C:\Users\Films & Muziek\AppData\Roaming\vlc\crashdump
Door de vrije schijfruimte te wissen worden restanten van bestanden verwijderd die zijn verwijderd zonder ze te vernietigen. Het maakt geen ruimte vrij.
Fout: system.free_disk_space: Function: Overschrijf de vrije schijfruimte op C:\Users\FILMS&~1\AppData\Local\Temp
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 145, in execute
  File "bleachbit\Cleaner.pyo", line 561, in wipe_path_func
  File "bleachbit\FileUtilities.pyo", line 1013, in wipe_path
KeyError: 'files '

Desktop Windows 11
BleachBit version 4.4.2

**Comment by az0** [comment]
See the FAQ:  [I closed BleachBit while it was working for a long time, and now my hard drive is full. How do I fix it?](https://docs.bleachbit.org/doc/frequently-asked-questions.html#:~:text=now%20my%20hard%20drive%20is%20full.%20How%20do%20I%20fix%20it%3F). Does this help?
