### ISSUE TITLE
Running Bleachbit ends in error

### ISSUE THREAD

**Issue by ravirajbasis** [bleachbit/bleachbit#1500]
Hi

Trying to install Bleachbit 4.x from source on FreeBSD OS.

The command python3 bleachbit.py, ends in following output:

root@localhost:~/Documents/bleachbit-4.4.2 # python3 bleachbit.py
Automatically preserving language en.
Traceback (most recent call last):
  File "/root/Documents/bleachbit-4.4.2/bleachbit.py", line 43, in <module>
    import bleachbit.GUI
  File "/root/Documents/bleachbit-4.4.2/bleachbit/GUI.py", line 26, in <module>
    from bleachbit import Cleaner, FileUtilities
  File "/root/Documents/bleachbit-4.4.2/bleachbit/Cleaner.py", line 33, in <module>
    from bleachbit import Command, FileUtilities, Memory, Special
  File "/root/Documents/bleachbit-4.4.2/bleachbit/Command.py", line 32, in <module>
    from sqlite3 import DatabaseError
  File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

How to mend the error?

Thanks
rraj

**Comment by ravirajbasis** [comment]
Hi

Installing databases/py-sqlite3 did the trick. Program runs normally!

Thanks
Ravi

**Comment by az0** [comment]
@ravirajbasis 
Thank you for letting me know that you figured it out.
