### ISSUE TITLE
Chromium clean errors: "no such table"

### ISSUE THREAD

**Issue by Utenet** [bleachbit/bleachbit#1531]
Hello,
I am getting the errors below when using bleachbit's built-in chromium cleaners. I have only noticed it recently, so it could be a recent chromium update. Any solutions?
Thanks!

```
clean_operation('chromium'),` options = '['cache', 'cookies', 'dom', 'form_history', 'history', 'search_engines', 'session', 'site_preferences', 'sync', 'vacuum']'
Clean file 0B /home/username/.config/chromium/Default/Preferences
Clean file 0B /home/username/.config/chromium/Default/Preferences
Clean file 0B /home/username/.config/chromium/Default/Preferences
Clean file 0B /home/username/.config/chromium/Local State
Clean file 0B /home/username/.config/chromium/Local State
Clean file 0B /home/username/.config/chromium/Default/databases/Databases.db
Error: chromium.form_history: Function: Clean file: /home/username/.config/chromium/Default/Web Data
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 474, in execute_sqlite3
    cursor.execute(cmd)
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 160, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/bleachbit/Special.py", line 106, in delete_chrome_autofill
    FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 481, in execute_sqlite3
    raise sqlite3.OperationalError(
sqlite3.OperationalError: no such table: autofill_profile_names: /home/username/.config/chromium/Default/Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 162, in execute
    if -1 == e.message.find('file is encrypted or is not a database') and \
AttributeError: 'OperationalError' object has no attribute 'message'
Clean file 0B /home/username/.config/chromium/Default/History
Clean file 0B /home/username/.config/chromium/Default/Favicons
Clean file 0B /home/username/.config/chromium/Default/Web Data
Clean file 4.1kB /home/username/.config/chromium/Default/Preferences
Clean file 0B /home/username/.config/chromium/Local State
Clean file 0B /home/username/.config/chromium/Default/Preferences
Clean file 0B /home/username/.config/chromium/Default/Preferences
Clean file 0B /home/username/.config/chromium/Default/Preferences
Vacuum 0B /home/username/.config/chromium/Default/History
Vacuum 0B /home/username/.config/chromium/Default/Login Data
Vacuum 0B /home/username/.config/chromium/Default/Web Data
Vacuum 0B `/home/username/.config/chromium/Default/databases/Databases.db
```

**Comment by az0** [comment]
I added a [notice and explanation ](https://www.bleachbit.org/news/bleachbit-442#no_such_table)to the BleachBit v4.4.2 release notes, and this is a priority fix for the next release. If more detail is needed for the notice, let me know.

**Comment by az0** [comment]
@Utenet 
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix.  Please test and let me know how it goes.

**Comment by Utenet** [comment]
bleachbit_4.4.2-0_all_ubuntu2004.deb
bleachbit_4.5.0-0_all_ubuntu2004.deb
bleachbit_4.5.0-0_all_debian12.deb
bleachbit_4.5.0-0_all_ubuntu2304.deb
bleachbit_4.5.0-0_all_ubuntu1804.deb

Hi Andrew,
Sorry, I tried all of the packages above on my system. They appear to install with GDebi without any errors, but do not run at all:

***@***.***:~$ bleachbit
Traceback (most recent call last):
File "/usr/bin/bleachbit", line 28, in <module>
from bleachbit import _
ModuleNotFoundError: No module named 'bleachbit'
***@***.***:~$

================================================================
System:
Kernel: 5.15.0-83-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33 wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

------- Original Message -------

**Comment by az0** [comment]
@Utenet 

Because "no such table" was fixed, would you please open a new ticket for this issue?

```
Traceback (most recent call last):
File "/usr/bin/bleachbit", line 28, in <module>
from bleachbit import _
ModuleNotFoundError: No module named 'bleachbit'
```
