### ISSUE TITLE
Bleachbit error: "sqlite3.OperationalError: no such table: autofill_profile_names"

### ISSUE THREAD

**Issue by unicorn76** [bleachbit/bleachbit#1533]
Bleachbit Error Message 20th Aug 2023

Error: brave.form_history: Function: Clean file: C:\Users\unico\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\unico\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

Error Message after new install 8th Aug 2023 
Error: brave.form_history: Function: Clean file: C:\Users\unico\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\unico\AppData\Local\BraveSoftware\Brave-Browser\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

**Comment by amayra** [comment]
1+

**Comment by az0** [comment]
Please see [BleachBit 4.4.2 release notes: no such table](https://www.bleachbit.org/news/bleachbit-442#no_such_table)

**Comment by unicorn76** [comment]
Hi Andrew

Success at last! Thank you so much. Worries are over.

Michael
***@***.***

**Comment by az0** [comment]
@unicorn76 
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix, and it has some changes since the original fix for this issue.

Please test and let me know how it goes.

**Comment by unicorn76** [comment]
Thanks, I'll check it out!

**Comment by unicorn76** [comment]
Hi Andrew

After extensive testing, I can verify that Bleachbit version 4.5.0 beta is
working well!

Thank you Andrew

Michael Jensen
