### ISSUE TITLE
Winapp2 issue [NotImplementedError: REG not supported in ExcludeKey]

### ISSUE THREAD

**Issue by KDapp5** [bleachbit/bleachbit#1541]
Winapp2.ini appears to have been frozen at version 210913 in the latest BleachBit release version 4.4.2.
I tried the latest 4.5.0.2500 from https://ci.bleachbit.org/?prefix=dl/4.5.0.2500-v4.5.0/
The Winapp2 version is still the same. The latest version is 230301.

I am not sure if this is an error, or intended.

A workaround is to manually import the latest Winapp2.ini into the "cleaners" folder. Make sure "download and update cleaners from the community" is unchecked, so the program doesn't overwrite the manually inserted file. It works, but Bleachbit throws this error message:

parsing error in section Windows Shell - Folder View Settings *
Traceback (most recent call last):
  File "bleachbit\Winapp.pyo", line 171, in __init__
  File "bleachbit\Winapp.pyo", line 296, in handle_section
  File "bleachbit\Winapp.pyo", line 297, in <listcomp>
  File "bleachbit\Winapp.pyo", line 217, in excludekey_to_nwholeregex
NotImplementedError: REG not supported in ExcludeKey

 - OS:  Windows 10,
 - BleachBit version [4.2.0]

**Comment by az0** [comment]
Yes, good catch. BleachBit updates through the version at https://github.com/bleachbit/winapp2.ini , and I will work on an update

**Comment by az0** [comment]
Update: The script in that repository requires changes to work with Python 3 and maybe because of upstream changes in Winapp2.ini, so it's not as easy as it usually is.

**Comment by rados** [comment]
@az0 I can try this one.

**Comment by az0** [comment]
Ok, thank you

**Comment by rados** [comment]
@az0 Only four lines in the latest winapp.ini (Version: 230301) have ExcludeKey with REG.  check_ini.py and merge_commit.sh pass without errors (given the four problematic lines are deleted). So, as a quick fix I can remove the four lines and all paths that are connected to them or I can remove the whole section and push. This way the users will have the most recent file, with only this exception, which is not big I think. Then we will have time for adjusting our scripts or even add support for ExcludeKey with REG. How does this sound?

@KDapp5 You can remove the whole section "[Windows Shell - Folder View Settings *]" or to remove the lines containing "REG|" and all paths above them that depend on them. Then the problem should be gone. If you have difficulties ping me.

**Comment by az0** [comment]
@az0 
Yes, a manual fix now with automated fix later is a good strategy. Thank you

**Comment by CrackHub** [comment]
If there is no ExcludeKey key, you can add them automatically. The current version of winapp2.ini is quite old.
New version vs BleachBit version
![1](https://github.com/bleachbit/bleachbit/assets/54614906/235f6d95-00d2-4467-9cc3-9041420b99fc)

**Comment by az0** [comment]
> If there is no ExcludeKey key, you can add them automatically. The current version of winapp2.ini is quite old. New version vs BleachBit version ![1](https://github.com/bleachbit/bleachbit/assets/54614906/235f6d95-00d2-4467-9cc3-9041420b99fc)

In August, I made an overhaul that made it easier to catch up, and I pushed an update for Winapp2.ini. Currently the [latest upstream](https://github.com/MoscaDotTo/Winapp2/blob/master/Non-CCleaner/Winapp2.ini version) was last modified March 2023
