### ISSUE TITLE
Error: microsoft_edge.form_history

### ISSUE THREAD

**Issue by EGorlomi** [bleachbit/bleachbit#1545]
Error: microsoft_edge.form_history: Function: Clean file: C:\Users\username\AppData\Local\Microsoft\Edge\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\username\AppData\Local\Microsoft\Edge\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

**Comment by az0** [comment]
This issue is documented in the [BleachBit version 4.4.2 release notes](https://www.bleachbit.org/news/bleachbit-442#no_such_table), and there is a fix in [BleachBit 4.5.0 beta](https://www.bleachbit.org/news/bleachbit-450-beta). If this does not help fix  the "no such table" issue, add a comment here.
