### ISSUE TITLE
sqlite3.OperationalError: no such table: autofill_profile_names

### ISSUE THREAD

**Issue by tekstryder** [bleachbit/bleachbit#1549]
- Arch Linux | Kernel 6.5.4
 - BleachBit 4.2.4

Seeing the following error(s) on each run lately:

```
Error: google_chrome.form_history: Function: Clean file: /home/myusername/.config/google-chrome/Default/Web Data
Traceback (most recent call last):
  File "/usr/share/bleachbit/FileUtilities.py", line 478, in execute_sqlite3
    cursor.execute(cmd)
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/Command.py", line 160, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 106, in delete_chrome_autofill
    FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/FileUtilities.py", line 485, in execute_sqlite3
    raise sqlite3.OperationalError(
sqlite3.OperationalError: no such table: autofill_profile_names: /home/myusername/.config/google-chrome/Default/Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 162, in execute
    if -1 == e.message.find('file is encrypted or is not a database') and \
             ^^^^^^^^^
AttributeError: 'OperationalError' object has no attribute 'message'
```

**Comment by rados** [comment]
@tekstryder, [BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta)has this fix.

**Comment by tekstryder** [comment]
Bah, github search failed me again. 

I see this is appears to be a dupe of https://github.com/bleachbit/bleachbit/issues/1531 ?

Closing this report, thanks.

**Comment by az0** [comment]
> I see this is appears to be a dupe of #1531 ?

Yes
