### ISSUE TITLE
Bleachbit error while cleaning Chromium

### ISSUE THREAD

**Issue by Chaudy** [bleachbit/bleachbit#1555]
While cleaning Chromium i get following report:

"Fehler: chromium.form_history: Function: Datei bereinigen: /home/hutter/.config/chromium/Default/Web Data
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 474, in execute_sqlite3
    cursor.execute(cmd)
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 160, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/bleachbit/Special.py", line 106, in delete_chrome_autofill
    FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 481, in execute_sqlite3
    raise sqlite3.OperationalError(
sqlite3.OperationalError: no such table: autofill_profile_names: /home/hutter/.config/chromium/Default/Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 162, in execute
    if -1 == e.message.find('file is encrypted or is not a database') and \
AttributeError: 'OperationalError' object has no attribute 'message'"

The error happens very time.

Linux Mint 21.2, Version 5.8.4, Kernel 5.15.0-84-generic

Any idea how to fix?

thx

**Comment by rados** [comment]
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta)has this fix.

**Comment by Chaudy** [comment]
THX
