### ISSUE TITLE
'system': '[Errno 13] Permission denied: '/proc/1398/fd/0'' after $ bleachbit -c system.tmp

### ISSUE THREAD

**Issue by erydit** [bleachbit/bleachbit#1558]
I am trying to scan and clear user`s System > Temporary files. But bleachbit throws an error:

```
Error during operation: 'system': '[Errno 13] Permission denied: '/proc/1398/fd/0''
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 345, in run_operations
    for _dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/Worker.py", line 159, in clean_operation
    for cmd in backends[operation].get_commands(option_id):
  File "/usr/share/bleachbit/Cleaner.py", line 499, in get_commands
    is_open = FileUtilities.openfiles.is_open(path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bleachbit/FileUtilities.py", line 170, in is_open
    self.scan()
  File "/usr/share/bleachbit/FileUtilities.py", line 163, in scan
    for filename in open_files():
  File "/usr/share/bleachbit/FileUtilities.py", line 136, in open_files
    target = os.path.realpath(filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 416, in realpath
  File "<frozen posixpath>", line 476, in _joinrealpath
PermissionError: [Errno 13] Permission denied: '/proc/1398/fd/0'

```

$ bleachbit -c system.tmp

The error happens every time.

**Screenshots**

**Desktop (please complete the following information):**
- OS: Manjaro 23.0.4 Uranos
- Kernel: x86_64 Linux 6.1.55-1-MANJARO
- DE: Xfce4
- BleachBit 4.4.2

**Comment by az0** [comment]
See https://github.com/bleachbit/bleachbit/issues/1515 . Does this help?

**Comment by erydit** [comment]
> See #1515 . Does this help?

Yes, the patch helped. Thank you!
