### ISSUE TITLE
Error messages when attempting to 'clean' - Google Chrome

### ISSUE THREAD

**Issue by unicorn76** [bleachbit/bleachbit#1572]
BleachBit Chrome errors 3rd Nov 2023

Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/host_referral_list 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 248, in execute
  File "bleachbit\FileUtilities.pyo", line 297, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/startup_list 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 248, in execute
  File "bleachbit\FileUtilities.pyo", line 297, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=net/http_server_properties/servers 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 248, in execute
  File "bleachbit\FileUtilities.pyo", line 297, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)

Error: google_chrome.history: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=savefile 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 248, in execute
  File "bleachbit\FileUtilities.pyo", line 297, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)

Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Web Data
Error: google_chrome.site_preferences: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=profile/content_settings/exceptions 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 248, in execute
  File "bleachbit\FileUtilities.pyo", line 297, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Local State
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=account_info 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 248, in execute
  File "bleachbit\FileUtilities.pyo", line 297, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=google_services 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 248, in execute
  File "bleachbit\FileUtilities.pyo", line 297, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=sync 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 248, in execute
  File "bleachbit\FileUtilities.pyo", line 297, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Vacuum 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\History

**Comment by az0** [comment]
1.
Do you use any other cleaner software similar to BleachBit?

2.
Would you be willing to email me the file `C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences`, so I can try to reproduce the error? My email address is my [GitHub profile page](https://github.com/az0/).

3.
Try [BleachBit version 4.6.0](https://www.bleachbit.org/news/bleachbit-460). Does this help?

**Comment by unicorn76** [comment]
Hi Andrew
Tried using the new 4.6.0 version and it works great! Thanks
Michael

**Comment by az0** [comment]
Thank you for confirming it works, so I will close the ticket.
