### ISSUE TITLE
[WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{B49C440B-4BE0-45B4-89AD-2FA8E11F57D0}

### ISSUE THREAD

**Issue by 13gears13** [bleachbit/bleachbit#1576]

**Comment by az0** [comment]
Which version of Windows? Which version of BleachBit? Are you running with admin rights?

The answer to this you can find in BleachBit under "diagnostic information," which you can copy and paste into here.

**Comment by 13gears13** [comment]
BleachBit version 4.6.0
Build number 2537
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
SQLite version 3.43.2
local_cleaners_dir = C:\Users\TSL\Desktop\BleachBit-Portable\cleaners
locale_dir = C:\Users\TSL\Desktop\BleachBit-Portable\share\locale\
options_dir = C:\Users\TSL\Desktop\BleachBit-Portable
personal_cleaners_dir = C:\Users\TSL\Desktop\BleachBit-Portable\cleaners
system_cleaners_dir = C:\Users\TSL\Desktop\BleachBit-Portable\share\cleaners\
locale.getdefaultlocale = ('en_US', 'cp1252')
os.getenv('APPDATA') = C:\Users\TSL\AppData\Roaming
os.getenv('cd') = C:\Users\TSL\Desktop\BleachBit-Portable
os.getenv('LocalAppData') = C:\Users\TSL\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\TSL\AppData\LocalLow
os.getenv('Music') = C:\Users\TSL\Music
os.getenv('USERPROFILE') = C:\Users\TSL
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\TSL\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\TSL
platform.win32_ver[1]() = 10.0.19041
platform.platform = Windows-10-10.0.19041
platform.version = 10.0.19041
sys.argv = ['C:\\Users\\TSL\\Desktop\\BleachBit-Portable\\bleachbit.exe']
sys.executable = C:\Users\TSL\Desktop\BleachBit-Portable\bleachbit.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Users\TSL\Desktop\BleachBit-Portable\library.zip\bleachbit\SystemInformation.pyo

**Comment by kajoken** [comment]
Adding my 2cts. Just updated to 4.6.0 and got the same error. BleachBit was started with admin rights. 

BleachBit version 4.6.0
Build number 2537
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
SQLite version 3.43.2
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\Kajoken\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\Kajoken\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('de_DE', 'cp1252')
os.getenv('APPDATA') = C:\Users\Kajoken\AppData\Roaming
os.getenv('cd') = C:\Program Files (x86)\BleachBit
os.getenv('LocalAppData') = C:\Users\Kajoken\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\Kajoken\AppData\LocalLow
os.getenv('Music') = C:\Users\Kajoken\Music
os.getenv('USERPROFILE') = C:\Users\Kajoken
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\Kajoken\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\Kajoken
platform.win32_ver[1]() = 10.0.22621
platform.platform = Windows-10-10.0.22621
platform.version = 10.0.22621
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit.exe']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\SystemInformation.pyo

**Comment by ramonsantana** [comment]
Found a solution, i had the same issue.
Download PowerRun, add Bleachbits to it and run it from within PowerRun.
It will make it run as trustedinstaller and i got no errors after that
https://www.sordum.org/9416/powerrun-v1-6-run-with-highest-privileges/

**Comment by 13gears13** [comment]
Good shit, thanks for posting.  Will attempt and post back here in a few days.

**Comment by az0** [comment]
Note to self

BleachBit version = 5.0.2.3273 (very different than 5.0.2 stable) has fixes for deleting files, but this error continues when cleaning _Windows Defender - History_ with overwriting enabled in the preferences.

(redundant log lines eliminated)

```
Error: windows_defender.history: Command to delete C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{E65CF43F-3C2C-442D-A2B2-26222B341EE7}
Traceback (most recent call last):
  File "bleachbit\Worker.pyc", line 88, in execute
  File "bleachbit\Command.pyc", line 98, in execute
  File "bleachbit\FileUtilities.pyc", line 507, in delete
  File "bleachbit\FileUtilities.pyc", line 400, in delete_file
  File "bleachbit\Wipe.pyc", line 179, in wipe_contents
  File "bleachbit\WindowsWipe.pyc", line 1196, in file_wipe
  File "bleachbit\WindowsWipe.pyc", line 529, in open_file
pywintypes.error: (5, 'CreateFileW', 'Access is denied.')
Error: windows_defender.history: Command to delete C:\ProgramData\Microsoft\Windows Defender\Scans\History\Service\History.Log
Traceback (most recent call last):
  File "bleachbit\Worker.pyc", line 88, in execute
  File "bleachbit\Command.pyc", line 98, in execute
  File "bleachbit\FileUtilities.pyc", line 507, in delete
  File "bleachbit\FileUtilities.pyc", line 400, in delete_file
  File "bleachbit\Wipe.pyc", line 179, in wipe_contents
  File "bleachbit\WindowsWipe.pyc", line 1196, in file_wipe
  File "bleachbit\WindowsWipe.pyc", line 529, in open_file
pywintypes.error: (5, 'CreateFileW', 'Access is denied.')
```

With overwriting disabled

```
Access denied: \\?\C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{6EE1E14A-D612-4A79-A53E-D091563C1BF1}
Access denied: \\?\C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{D46E9A43-15C6-44FA-93FF-0E5B991F2318}
Access denied: \\?\C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{E65CF43F-3C2C-442D-A2B2-26222B341EE7}
Access denied: \\?\C:\ProgramData\Microsoft\Windows Defender\Scans\History\Service\History.Log
```
