### ISSUE TITLE
Can't vacuum Firefox favicons.sqlite

### ISSUE THREAD

**Issue by rlvitalo** [bleachbit/bleachbit#1598]
Running Windows 7Pro, Firefox 115.5 OESR Bleachbit 4.6

Get this error message:

Error: thunderbird.vacuum: Function: Vacuum: C:\Users\Raphael\AppData\Roaming\Thunderbird\Profiles\1ai94l1x.default\favicons.sqlite
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 478, in execute_sqlite3
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 166, in execute
  File "bleachbit\FileUtilities.pyo", line 1050, in vacuum_sqlite3
  File "bleachbit\FileUtilities.pyo", line 486, in execute_sqlite3
sqlite3.OperationalError: unable to open database file: C:\Users\Raphael\AppData\Roaming\Thunderbird\Profiles\1ai94l1x.default\favicons.sqlite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 168, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

**Comment by rados** [comment]
@az0, I can handle this one.

**Comment by rlvitalo** [comment]
Should have added I am running Thunderbird 115.4.3 (32-bit)

**Comment by rlvitalo** [comment]
@rados 
I reinstalled bleachbit 4.6 and I no longer get the error messages. No other change has occurred. Unless someone else reports the problem, this may not be worth your time.
Raphael

**Comment by rados** [comment]
> @rados I reinstalled bleachbit 4.6 and I no longer get the error messages. No other change has occurred. Unless someone else reports the problem, this may not be worth your time. Raphael

Thank you. :)

**Comment by az0** [comment]
> I reinstalled bleachbit 4.6 and I no longer get the error messages. No other change has occurred. Unless someone else reports the problem, this may not be worth your time. Raphael

@rlvitalo 

Thank you for following up, Raphael. 

I tested with Thunderbird 141.0 (64-bit) on Windows 11 with BleachBit 5.0.0 (final release, build 2936), but I could not reproduce it either. I allowed Thunderbird to show remote content for several emails. 

Since then, I have made  changes (b82c164cb570f444319a1ec4b04cfb2dbca2ff14) to fix a similar error when vacuuming Firefox, so that may help with this issue, in case the conditions arise for someone else.

Therefore, I will close this ticket.
