### ISSUE TITLE
Bleachbit app hanged when running Clean operation with selected all options after Preview was completed on Ubuntu 20

### ISSUE THREAD

**Issue by JuraLys** [bleachbit/bleachbit#1627]
see attached screenshot 
![Bleachbit-hang(](https://github.com/bleachbit/bleachbit/assets/146434286/88c4e3d9-de1f-485a-b9e0-7e27dc378c10)

**Comment by az0** [comment]
Disable options under the "deep scan" section. Does this help?

**Comment by JuraLys** [comment]
> Disable options under the "deep scan" section. Does this help?

It helped but cleaning completed with error:
Error: system.free_disk_space: Function: Overwrite free disk space /root/.cache
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 145, in execute
    for func_ret in self.func():
  File "/usr/share/bleachbit/bleachbit/Cleaner.py", line 569, in wipe_path_func
    for ret in FileUtilities.wipe_path(pathname, idle=True):
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 978, in wipe_path
    truncate_f(f)
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 678, in truncate_f
    f.truncate(0)
  File "/usr/lib/python3.8/tempfile.py", line 612, in func_wrapper
    return func(*args, **kwargs)
OSError: [Errno 28] No space left on device

Disk space recovered: 388MB
Files deleted: 140
Special operations: 7
Errors: 1
elapsed time: 797 seconds

**Comment by az0** [comment]
@JuraLys 
Under the _System_ category, uncheck the box for _Free disk space_. Does this help?
