### ISSUE TITLE
Google Chrome bug

### ISSUE THREAD

**Issue by unicorn76** [bleachbit/bleachbit#1658]
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/host_referral_list 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/startup_list 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=net/http_server_properties/servers 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\databases\Databases.db
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Web Data
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\History
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Favicons
Error: google_chrome.history: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=savefile 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Web Data
Error: google_chrome.site_preferences: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=profile/content_settings/exceptions 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Local State
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=account_info 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=google_services 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=sync 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Vacuum 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\History
Vacuum 0B C:\Users\unico\App**Describe the bug**
A clear and concise description of what the bug is (about one sentence long).

**To Reproduce**

The error happens (sometimes/every time).

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g., Windows 10, Ubuntu 20.04]
 - BleachBit version [e.g., 4.2.0]

**Additional context**

**Comment by unicorn76** [comment]
Have tried shutting down the laptop then restarting, and then re-engaging Bleachbit to no avail.  I had a similar problem before with Edge but remedied by Andrew Ziem and another great person.

**Comment by rados** [comment]
@unicorn76, thank you for the report. If the problem persists the issue can stay open...

**Comment by unicorn76** [comment]
Problem is still persisting, anyone have any ideas as I love Bleachbit and miss it's thorough cleaning of my laptop.

**Comment by rados** [comment]
@az0 I can take look here.

**Comment by unicorn76** [comment]
Thank you rados

**Comment by rados** [comment]
@unicorn76 I couldn't reproduce it with my initial attempt - Bleachbit handled this json normaly. Could you share the versions of Bleachbit, Chrome and Windows?

**Comment by unicorn76** [comment]
Hi rados,
Bleachbit 4.60
Windows 11 Pro 64-bit
Brave 124.1.65.114

I do not use Chrome and Edge only when absolutely necessary for a particular application which is very rare

**Comment by unicorn76** [comment]
I also use Nord VPN and Kaspersky

**Comment by unicorn76** [comment]
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/host_referral_list 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/startup_list 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=net/http_server_properties/servers 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Local State
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\databases\Databases.db
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Web Data
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\History
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Favicons
Error: google_chrome.history: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=savefile 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.history: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=savefile 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Web Data
Error: google_chrome.site_preferences: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=profile/content_settings/exceptions 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Clean file 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Local State
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=account_info 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=google_services 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=sync 
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 250, in execute
  File "bleachbit\FileUtilities.pyo", line 301, in clean_json
  File "json\__init__.pyo", line 268, in load
  File "json\__init__.pyo", line 314, in loads
ValueError: Unexpected UTF-8 BOM (decode using utf-8-sig)
Vacuum 0B C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\History

Hi rados, I have included more of the error messaging I get when trying to 'clean' with Bleachbit. Unsure of its value to solving the problem.

Best regards

**Comment by rados** [comment]
@unicorn76 Hey, thank you. Still the error message is about Google Chrome. See this this part:

"Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/host_referral_list"

So, my suggestion is to uninstall and install Chrome. If not fixed try manually deleting this json file in question, it could be corrupted, improperly saved, too old, etc.

**Comment by unicorn76** [comment]
Hi rados,

I don't have Google Chrome installed on my laptop which makes it even more confusing. However, I will try your alternative suggestion of deleting the json file.

**Comment by unicorn76** [comment]
Hi rados, 
Just checked __C:\Users\unico\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/host_referral_list__", and I do NOT have that file. Neither do I have a Preferences folder?

**Comment by rados** [comment]
Preferences is the json file, a bit unusual it doesn't have 'json' extension.

![image](https://github.com/bleachbit/bleachbit/assets/332322/d558c52d-b13a-4339-8be6-1617a4d6a8e7)

**Comment by rados** [comment]
@unicorn76 I've created a possible fix (to handle this type of json). You can try the following build:

https://ci.appveyor.com/project/az0/bleachbit/builds/49706517/artifacts

**Comment by unicorn76** [comment]
Hi rados,

Tried your fix and Bleachbit now works perfectly! 
Thank you
Best regards
@unicorn76

**Comment by az0** [comment]
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) which has this  fix for the ValueError with Google Chrome.**  If you still see this ValueError with Chrome, reopen this issue.

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
