### ISSUE TITLE
Bleachbit will not open nor run...

### ISSUE THREAD

**Issue by cpari44** [bleachbit/bleachbit#1661]
_I have Bleachbit (not portable) version 4.6.0.2537 installed on a Win10 (x64) PC. 
After opening up cmd from the Search box and navigating to C:\Program Files (x86)\BleachBit\bleachbit_console.exe 
below is what it printed out:_

C:\Program Files (x86)\BleachBit\bleachbit_console.exe
Traceback (most recent call last):
  File "bleachbit_console.py", line 56, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "bleachbit\GUI.pyo", line 32, in <module>
  File "bleachbit\Options.pyo", line 163, in get
  File "configparser.pyo", line 801, in getboolean
  File "configparser.pyo", line 775, in _get
  File "configparser.pyo", line 1132, in _convert_to_boolean
ValueError: Not a boolean: ['False']

_Before trying to run Bleachbit (v4.4.2) I updated my Python software to version 3.12.3150.0 and PyCharm CE to version 241.14494.241._

_What can I do to fix this issue?_
_Bleachbit (v4.4.2) ran fine before I updated it, the Python software and PyCharm CE to their latest versions._
_I reinstalled Bleachbit version 4.4.2 which results in the same issue of not running with the Python software version 3.12.3150.0 and PyCharm CE version 241.14494.241 still intact. Maybe Bleachbit conflicts with the latest versions of Python and/or PyCharm CE?_

**Comment by az0** [comment]
BleachBit should be using its own private copy of Python that's in the BleachBit folder. 

Please try this

1. Open %appdata%\bleachbit
2. Copy `bleachbit.ini` to another name like `bleachbit.ini.backup`
3. Run BleachBit

If it works, please send me the `bleachbit.ini.backup` file (the old broken one) by attaching it here or emailing to ahz0001 at duck dot com. To attach here, rename the .ini file to .log or .txt.

**Comment by cpari44** [comment]
> BleachBit should be using its own private copy of Python that's in the BleachBit folder.
> 
> Please try this
> 
> 1. Open `%appdata%\bleachbit`
> 2. Copy `bleachbit.ini` to another name like `bleachbit.ini.backup`
> 3. Run BleachBit
> 
> If it works, please send me the `bleachbit.ini.backup` file (the old broken one) by attaching it here or emailing to ahz0001 at duck dot com. To attach here, rename the .ini file to .log or .txt.

It worked! Upon successfully running and opening Bleachbit it created a new `bleachbit.ini` file in place of `bleachbit.ini.backup`.

Attached is the old broken `bleachbit.ini.backup` file which is renamed `bleachbit.ini.backup.txt` as per your instructions. 
Would it be safe to delete `bleachbit.ini.backup` from the `%appdata%\bleachbit` directory or should I leave it there? 

Thanks for your input. 

[bleachbit.ini.backup.txt](https://github.com/bleachbit/bleachbit/files/15145853/bleachbit.ini.backup.txt)
