### ISSUE TITLE
path error in apt.autoremove

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#168]
The error does not happen the second time because there is nothing left to remove.

```
clean_operation('apt'), options = '['autoremove']'
Error in execution of <bleachbit.Command.Function instance at 0x7ff6957ec8c0>
Traceback (most recent call last):
  File "bleachbit/bleachbit/Worker.py", line 84, in execute
    for ret in cmd.execute(self.really_delete):
  File "bleachbit/bleachbit/Command.py", line 133, in execute
    func_ret = self.func()
  File "bleachbit/bleachbit/Unix.py", line 607, in apt_autoremove
    raise RuntimeError("Error calling '%s':\n%s" % (' '.join(e.cmd), e.output))
RuntimeError: Error calling 'apt-get --yes autoremove':
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  libsqlite0 libuser1 linux-headers-4.4.0-21 linux-headers-4.4.0-21-generic
  linux-headers-4.4.0-22 linux-headers-4.4.0-22-generic linux-headers-4.4.0-24
  linux-headers-4.4.0-24-generic linux-headers-4.4.0-28
  linux-headers-4.4.0-28-generic linux-headers-4.4.0-31
  linux-headers-4.4.0-31-generic linux-headers-4.4.0-34
  linux-headers-4.4.0-34-generic linux-headers-4.4.0-36
  linux-headers-4.4.0-36-generic linux-headers-4.4.0-38
  linux-headers-4.4.0-38-generic linux-headers-4.4.0-42
  linux-headers-4.4.0-42-generic linux-headers-4.4.0-45
  linux-headers-4.4.0-45-generic linux-headers-4.4.0-47
  linux-headers-4.4.0-47-generic linux-headers-4.4.0-51
  linux-headers-4.4.0-51-generic linux-image-4.4.0-42-generic
  linux-image-4.4.0-45-generic linux-image-4.4.0-47-generic
  linux-image-4.4.0-51-generic linux-image-extra-4.4.0-42-generic
  linux-image-extra-4.4.0-45-generic linux-image-extra-4.4.0-47-generic
  linux-image-extra-4.4.0-51-generic python-decoratortools python-iniparse
  python-lzma python-peak.util.decorators python-sqlite python-sqlitecachec
  usermode yum yum-utils
0 upgraded, 0 newly installed, 43 to remove and 3 not upgraded.
After this operation, 1811 MB disk space will be freed.
dpkg: error: PATH is not set
E: Sub-process /usr/bin/dpkg returned an error code (2)

Disk space recovered: 0
Files deleted: 0
Errors: 1

````

**Comment by tstenner** [comment]
Same problem as #167 - subprocesses currently either inherit the locale (which might not be english) or don't inherit the PATH variable. I'll look into removing locale vars before calling subprocesses.

**Comment by az0** [comment]
@tstenner Thank you for taking a look!

**Comment by az0** [comment]
Regarding 45546b941085b6f3b90364e342356e3d0adf77f7, you need to set all the environment variables. From the docs: "If specified, env must provide any variables required for the program to execute."

How about changing the function to:

````def run_external(args, stdout=False, env=None, clean_env=False):````

And when `clean_env = True`, then on POSIX  systems it sets the PATH,  LC_ALL, HOME, LD_LIBRARY_PATH, and TMPDIR, if they exist.

Then I would add a unit test,  something like
````
run_external(['bash','-c','echo $PATH'])
run_external(['bash','-c','echo $LC_ALL])
````
I will assume you will look more into this. If you prefer I continue on this, let me know.  Thanks again.
