### ISSUE TITLE
Exception while running operation 'system': ''utf-8' codec can't encode character '\udcd6' in position 52: surrogates not allowed'

### ISSUE THREAD

**Issue by abclution** [bleachbit/bleachbit#1709]
**Describe the bug**
Doing a system Cache analyze/clean produces this message.
I think this must be a file with extended characters in the name but I have not yet found it. If I do I will update.
Regardless, something isn't sanitized properly to handle this. :)

**To Reproduce**
If I could figure out which file is causing this I would paste its name.

Doing a system Cache analyze/clean produces this message.
The error happens every time.

**Expected behavior**
Should not fail

**Desktop (please complete the following information):**
 - OS: Debian 12 KDE 
 - BleachBit version 4.6.0

clean_operation('system'), options = '['cache']'
Exception while running operation 'system': ''utf-8' codec can't encode character '\udcd6' in position 52: surrogates not allowed'
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 345, in run_operations
    for _dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/Worker.py", line 160, in clean_operation
    for ret in self.execute(cmd, '%s.%s' % (operation, option_id)):
  File "/usr/share/bleachbit/Worker.py", line 132, in execute
    self.ui.append_text(line)
  File "/usr/share/bleachbit/GUI.py", line 667, in append_text
    self.textbuffer.insert(__iter, text)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 764, in insert
    Gtk.TextBuffer.insert(self, iter, text, length)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcd6' in position 52: surrogates not allowed

Disk space to be recovered: 16.4kB
Files to be deleted: 1
Errors: 1
elapsed time: 0 seconds

**Comment by abclution** [comment]
OK, I used

`LC_ALL=C find . -name '*[! -~]*'`

to narrow down what files are non english, I do have many valid non english filenames, however...

There is a bunch of files present from the James DSP program for linux in the .cache folder.
~/.cache/
./jamesdsp/autoeq/B?HM B-66
./jamesdsp/autoeq/Vision Ears Erlk?nig
./jamesdsp/autoeq/R?DE NTH-100M
./jamesdsp/autoeq/Vision Ears Erlk?nig 4
./jamesdsp/autoeq/Vision Ears Erlk?nig 3
./jamesdsp/autoeq/Vision Ears Erlk?nig 1
./jamesdsp/autoeq/Vision Ears Erlk?nig 2
./jamesdsp/autoeq/Tripowin Le?


KDE dolphin was not able to understand or change directories into them, but my bash shell was able through escaping them.
./jamesdsp/autoeq/B?HM B-66

showed up as B�HM B-66/  but autocomplete was able to translate it into  B\Xd6HM B-66/

Anyways, no idea what language those are or if they are just command chars or whatever.

**Comment by az0** [comment]
That is good troubleshooting so far, and would you please add more info?

1. Open BleachBit
2. Open the hamburger menu (three horizontal lines)
3.  Choose **System Information**
4. Look for a line that starts with **locale.getdefaultlocale**
5. Copy that line
6. Paste it in a comment here

**Comment by abclution** [comment]
locale.getdefaultlocale = ('en_US', 'UTF-8')
