### ISSUE TITLE
Cannot shred folder [UnboundLocalError in get_extents]

### ISSUE THREAD

**Issue by Cronos-ALT** [bleachbit/bleachbit#1719]
**Describe the bug**
I tried to shred a folder that contains a 7zip file that's around 80 gb and every time i try to shred that folder or shred the file inside, I keep getting the error in the image down below.
To reproduce it try to shred the entire folder or access the folder and try to delete de 7zip file itself.

**Expected behavior**
It should shred the entire folder.

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/8f6c7cbb-9076-43d3-8d6f-2a16ea06e12c)

(Edit: az0 converted image to text)
```
Traceback (most recent call last):
File "bleachbit\Worker.pyo", line 87, in execute
File "bleachbit\Command.pyo", line 86, in execute
File "bleachbit\FileUtilities.pyo", line 388, in delete
File "bleachbit\FileUtilities.pyo", line 816, in wipe_contents
File "bleachbit\WindowsWipe.pyo", line 917, in file_wipe
File "bleachbit\WindowsWipe.pyo", line 584, in get_extents
UnboundLocalError: local variable 'rp_struct' referenced before assignment
```

**Desktop (please complete the following information):**
 - OS: [windows 11, I'm on update 23h2]
 - BleachBit version [4.6.0]

**Additional context**
This problem appears only when i'm trying to delete this folder that contains the 7zip file in particular. The culprit folder in this situation it's called "[ScrewThisNoise] HoneySelect 2 DX BetterRepack R16" . I'm out of options, please help !

**Comment by az0** [comment]
This is a bug requiring a code fix. Thank you for the big report

File "bleachbit\WindowsWipe pyo", line 584, in get extents UnboundLocalError: local variable 'rp struct referenced before assignment


Is there anything special about that physical drive or partition? Is it the default partition that came with your computer, or did you do any partitioning or formatting yourself? 

Have you run any special software on that drive to defragment, encrypt it, or anything else like that?

**Comment by az0** [comment]
You closed the ticket, but I assume it was by accident, so I am reopening it.

> This problem appears only when i'm trying to delete this folder that contains the 7zip file in particular. The culprit folder in this situation it's called "[ScrewThisNoise] HoneySelect 2 DX BetterRepack R16" . I'm out of options, please help !

How large is that folder? 

How many files are in that folder?

Did you download the 7zip file using a web browser, torrent, or something else?

Is compression enabled? 

Are the filenames blue, green, or white?

**Comment by az0** [comment]
The good news is that there is not a harmful side effect. For example, there is no file corruption.

I am still looking into it.  Note to myself: The UnboundLocalError happens because the rp_struct variable is only assigned within a try block. If the DeviceIoControl function fails with an error code that isn't explicitly handled (i.e., 38, 122, or 234) in any of the loop iterations, rp_struct remains unassigned.

**Comment by az0** [comment]
@Cronos-ALT 
Did you see my questions on March 11? If you have more info, please do share. 

I will mark this closed with the code changes to improve exception handling. If you see this error in the future, especially with the message "Unhandled error code %d in get_extents for file", please let me know the error code and other details.

**Comment by az0** [comment]
[BleachBit 5.0.1 beta](https://www.bleachbit.org/news/bleachbit-501-beta) was released with the improved exception handling. If you get a chance, check it out.
