### ISSUE TITLE
scanning files breaks when stumbling on badly encoded filenames

### ISSUE THREAD

**Issue by wsourdeau** [bleachbit/bleachbit#1738]
I have a filesystem with filenames that contain apparently invalid utf-8 characters. Whenever Bleachbit stumbles on such filenames, the scanning is interrupted without any warning, any GUI reset nor any message that would allow be to fix and restart the process. The only cue that I received was the following exception message :

```
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 269, in run
    yield from self.run_deep_scan()
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 328, in run_deep_scan
    for _ret in self.execute(cmd, 'deepscan'):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 132, in execute
    self.ui.append_text(line)
  File "/usr/share/bleachbit/bleachbit/GUI.py", line 667, in append_text
    self.textbuffer.insert(__iter, text)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 753, in insert
    Gtk.TextBuffer.insert(self, iter, text, length)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udc82' in position 78: surrogates not allowed

```

I think that, at minimum, it would be nice if the scanning process would report and ignore such files, and continue until the end. If the filename itself is undisplayable, the named of the parent directory would be useful too.

Thank you!

**Comment by az0** [comment]
Do you have any advice on creating such files to reproduce the bug? If you can't copy and paste the filename, maybe you can archive them with tar, zip, or 7zip.
