### ISSUE TITLE
Windows Defender issue

### ISSUE THREAD

**Issue by unicorn76** [bleachbit/bleachbit#1750]
Hi Guys, having trouble when executing a 'Clean' using bleachbit. Have tried re-installing Windows 11 Pro, and Windows Defender, plus bleachbit 4.6.2.2665 to no avail. Does any kindly person have a solution for me? Thanks

exception when deleting locked file C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{1F3F3865-3E21-43E8-9CFE-E263368142C8}
Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 86, in execute
  File "bleachbit\FileUtilities.pyo", line 404, in delete
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\\History\\Results\\Quick\\{1F3F3865-3E21-43E8-9CFE-E263368142C8}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 94, in execute
  File "bleachbit\Windows.pyo", line 180, in delete_locked_file
PermissionError: [WinError 5] Access is denied.
Delete 11.5kB C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{1F3F3865-3E21-43E8-9CFE-E263368142C8}
exception when deleting locked file C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{5142AA78-389D-4F57-94B5-E668D3C2BCCC}
Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 86, in execute
  File "bleachbit\FileUtilities.pyo", line 404, in delete
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\\History\\Results\\Quick\\{5142AA78-389D-4F57-94B5-E668D3C2BCCC}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 94, in execute
  File "bleachbit\Windows.pyo", line 180, in delete_locked_file
PermissionError: [WinError 5] Access is denied.
Delete 11.2kB C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{5142AA78-389D-4F57-94B5-E668D3C2BCCC}
exception when deleting locked file C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{DB6EA4FD-E46C-4CB9-9A86-200DC9BC8788}
Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 86, in execute
  File "bleachbit\FileUtilities.pyo", line 404, in delete
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\\History\\Results\\Quick\\{DB6EA4FD-E46C-4CB9-9A86-200DC9BC8788}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 94, in execute
  File "bleachbit\Windows.pyo", line 180, in delete_locked_file
PermissionError: [WinError 5] Access is denied.
Delete 11.2kB C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Quick\{DB6EA4FD-E46C-4CB9-9A86-200DC9BC8788}
exception when deleting locked file C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{39B5D943-8B02-4020-A60E-88B1DCC0EC90}
Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 86, in execute
  File "bleachbit\FileUtilities.pyo", line 404, in delete
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\\History\\Results\\Resource\\{39B5D943-8B02-4020-A60E-88B1DCC0EC90}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 94, in execute
  File "bleachbit\Windows.pyo", line 180, in delete_locked_file
PermissionError: [WinError 5] Access is denied.
Delete 11.2kB C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{39B5D943-8B02-4020-A60E-88B1DCC0EC90}
exception when deleting locked file C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{B76A2E9E-C87A-4DA4-B796-1A5BC10CC5CA}
Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 86, in execute
  File "bleachbit\FileUtilities.pyo", line 404, in delete
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\\History\\Results\\Resource\\{B76A2E9E-C87A-4DA4-B796-1A5BC10CC5CA}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 94, in execute
  File "bleachbit\Windows.pyo", line 180, in delete_locked_file
PermissionError: [WinError 5] Access is denied.
Delete 11.5kB C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{B76A2E9E-C87A-4DA4-B796-1A5BC10CC5CA}
exception when deleting locked file C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{F18A0A61-B645-4830-985F-D2650E5B1327}
Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 86, in execute
  File "bleachbit\FileUtilities.pyo", line 404, in delete
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\\History\\Results\\Resource\\{F18A0A61-B645-4830-985F-D2650E5B1327}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 94, in execute
  File "bleachbit\Windows.pyo", line 180, in delete_locked_file
PermissionError: [WinError 5] Access is denied.
Delete 11.2kB C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{F18A0A61-B645-4830-985F-D2650E5B1327}
exception when deleting locked file C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{F98ECDED-3B36-45D1-A8D1-761BE0244319}
Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 86, in execute
  File "bleachbit\FileUtilities.pyo", line 404, in delete
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\\History\\Results\\Resource\\{F98ECDED-3B36-45D1-A8D1-761BE0244319}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 94, in execute
  File "bleachbit\Windows.pyo", line 180, in delete_locked_file
PermissionError: [WinError 5] Access is denied.
Delete 11.5kB C:\ProgramData\Microsoft\Windows Defender\Scans\History\Results\Resource\{F98ECDED-3B36-45D1-A8D1-761BE0244319}
exception when deleting locked file C:\ProgramData\Microsoft\Windows Defender\Scans\History\Service\History.Log
Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 86, in execute
  File "bleachbit\FileUtilities.pyo", line 404, in delete
PermissionError: [WinError 5] Access is denied: '\\\\?\\C:\\ProgramData\\Microsoft\\Windows Defender\\Scans\\History\\Service\\History.Log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 94, in execute
  File "bleachbit\Windows.pyo", line 180, in delete_locked_file
PermissionError: [WinError 5] Access is denied.

**Comment by az0** [comment]
When BleachBit starts, **does Windows show a dialog with the text** "User Account Control : Do you want to allow this app to make changes to your device?"

**If so, do you answer _yes_?**



As background, other users have reported similar issues with issues with Windows Defender, though the paths differ. 

Error: windows_defender.backup: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpavdlta.vdm
https://github.com/bleachbit/bleachbit/issues/337#issuecomment-560461585

[WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpasbase.vdm
https://github.com/bleachbit/bleachbit/issues/1004

[WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpasbase.vdm
https://github.com/bleachbit/bleachbit/issues/1021

[WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Definition Updates\Backup\mpasbase.vdm
https://github.com/bleachbit/bleachbit/issues/1125

WinError 5] Access is denied.: Command to delete C:\ProgramData\Microsoft\Windows Defender\Scans\History\Service\History.Log
https://github.com/bleachbit/bleachbit/issues/1512

We can continue to look into your issue, but so far some  potential options include
1. Boot into safe mode and run BleachBit
2. Ignore the errors
3. Disable the cleaning option in BleachBit that generates the errors
4. Whitelist the files

**Comment by indig0F10w** [comment]
The same error is when trying to clean quarantine folder.

This error occures because the user does not have permissions to delete anything from Windows Defender folder. I have UAC disabled because it is a pain in the eye and I have about 3GB of false detections in Defender Quarantine.

You cannot easily delete the contents of this folder. The quickest way is to go to Group policy editor > Computer Configuration > Administrative templates >Windows Components > Microsoft Defender Antivirus > Quarantine > Configure removal of items from Quarantine folder (setting is in days).

To apply the settings restart PC or open Admin command prompt and type "gpupdate /force" and press enter. Wait the number of days you selected in settings and it will be deleted automatically.

Another way is to boot a live Linux or whatever OS distro and delete it manually.
