### ISSUE TITLE
 BleachBit 1.15.404 error

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#177]
from ROCKNROLLKID

Traceback (most recent call last):
File "bleachbit.py", line 42, in
File "gtk\__init__.pyo", line 30, in
File "gobject\__init__.pyo", line 26, in
File "glib\__init__.pyo", line 22, in
File "glib\_glib.pyo", line 12, in
File "glib\_glib.pyo", line 10, in __load
ImportError: DLL load failed: Invalid access to memory location.

**Comment by az0** [comment]
Duplicate of #180
