### ISSUE TITLE
BleachBit 1.15.404 on Windows will not start

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#180]
ROCKNROLLKID's error
https://www.bleachbit.org/forum/bleachbit-115404-error

After some popup errors, I get a similar error in the log
````
Traceback (most recent call last):
  File "bleachbit.py", line 33, in <module>
  File "bleachbit\Windows.pyo", line 64, in <module>
  File "bleachbit\Command.pyo", line 29, in <module>
  File "bleachbit\FileUtilities.pyo", line 34, in <module>
  File "random.pyo", line 885, in <module>
  File "random.pyo", line 97, in __init__
  File "random.pyo", line 113, in seed
WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly
````

**Comment by az0** [comment]
1.15.401 (wipe branch) has the same symptoms on Windows XP. The popup has an error :
``` procedure entry point _except_handler4_common could not be located in the dynamic link library msvcrt.dll```

404 and 401 are both on the wipe branch, so it may be related to files needed by its new imports
