### ISSUE TITLE
ImportError: No module named WindowsWipe

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#182]
https://ci.appveyor.com/project/az0/bleachbit/build/1.15.415#L1550
```Unit test for method create_simple_cleaner ... Error wiping path \\?\c:\users\appveyor\appdata\local\temp\1\bleachbit-test-create-simple-cleanerejtfmi\1 using defragmentation API so falling back to other method
Traceback (most recent call last):
  File ".\bleachbit\FileUtilities.py", line 626, in wipe_contents
ImportError: No module named WindowsWipe
Error wiping path \\?\c:\users\appveyor\appdata\local\temp\1\bleachbit-test-create-simple-cleanerejtfmi\чистый using defragmentation API so falling back to other method
Traceback (most recent call last):
  File ".\bleachbit\FileUtilities.py", line 626, in wipe_contents
ImportError: No module named WindowsWipe
ok
test_get_commands (TestCleaner.CleanerTestCase) ... ok
test_get_descrption (TestCleaner.CleanerTestCase) ... ok
````

**Comment by az0** [comment]
Not reproducible on my Windows 7

**Comment by az0** [comment]
The error is not in these logs
https://ci.appveyor.com/project/az0/bleachbit/build/1.15.432
https://ci.appveyor.com/project/az0/bleachbit/build/1.15.430

It is here
https://ci.appveyor.com/project/az0/bleachbit/build/1.15.420

No longer reproducible
