### ISSUE TITLE
AssertionError: 6L != 3

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#196]
https://ci.appveyor.com/project/az0/bleachbit/build/1.15.469
https://ci.appveyor.com/project/az0/bleachbit/build/1.15.474
````
======================================================================
FAIL: test_Locked (tests.TestWorker.WorkerTestCase)
Test Worker using Action.LockedAction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestWorker.py", line 256, in test_Locked
    self.action_test_helper('locked', 0, 0, None, None, 3 + 0, 2)
  File "C:\projects\bleachbit\tests\TestWorker.py", line 225, in action_test_helper
    self.assertEqual(worker.total_bytes, bytes_expected_nt)
AssertionError: 6L != 3
````

**Comment by az0** [comment]
Fixed in 193e07ad484897a57bdb5b5bd280677f2a6ac3ea
