### ISSUE TITLE
[Win] [1.12] error MsgBox occurs with command line

### ISSUE THREAD

**Issue by nolme** [bleachbit/bleachbit#248]
Hi,
when running :
bleachbit_console.exe --preset --clean

it may encounter errors when deleting files. A MessageBox is displayed, so my script is blocked.
![bleachbit error](https://user-images.githubusercontent.com/4461224/32279768-edbb86a4-bf19-11e7-8a04-c69dfb2d78ae.PNG)

In the LOG file, I see some Errno 2 like this one : 
[Errno 2] No such file or directory: '\\\\?\\C:\\Users\\vincent.duvernet\\Local Settings\\Temp\\wctFF4C.tmp': Command to delete C:\Users\vincent.duvernet\Local Settings\Temp\wctFF4C.tmp

Vincent.

**Comment by nolme** [comment]
Hi, you're right, I've changed the topic title because it's 1.12 version, the only one available on : [https://www.bleachbit.org/download/windows]
I'll try with the 1.17.

**Comment by nolme** [comment]
Hi, you're right, I've changed the topic title because it's 1.12 version, the only one available on : [https://www.bleachbit.org/download/windows]
I'll try with the 1.17.

**Comment by nolme** [comment]
Here's the result of today's test on an XP machine where some scripts are no more supported. But it display an error MsgBox at the end : 

> Erreur lors de l’exécution de « firefox » : « this Windows version is too old (< Windows Vista); psutil 3.4.2 is the latest version which supports Windows 2000, XP and 2003 server »
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 339, in run_operations
  File "bleachbit\Worker.pyo", line 134, in clean_operation
  File "bleachbit\Cleaner.pyo", line 161, in is_running
  File "bleachbit\Windows.pyo", line 453, in is_process_running
  File "bleachbit\Windows.pyo", line 513, in is_process_running_psutil
  File "psutil\__init__.pyo", line 126, in <module>
  File "psutil\_pswindows.pyo", line 30, in <module>
RuntimeError: this Windows version is too old (< Windows Vista); psutil 3.4.2 is the latest version which supports Windows 2000, XP and 2003 server
Error in execution of <bleachbit.Command.Function instance at 0x02277C10>
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 83, in execute
  File "bleachbit\Command.pyo", line 138, in execute
  File "bleachbit\Windows.pyo", line 218, in wu_service
  File "bleachbit\General.pyo", line 150, in run_external
  File "subprocess.pyo", line 382, in __init__
  File "subprocess.pyo", line 515, in _get_handles
  File "subprocess.pyo", line 566, in _make_inheritable
WindowsError: [Error 6] Descripteur non valide
Error in execution of <bleachbit.Command.Function instance at 0x02277CB0>
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 83, in execute
  File "bleachbit\Command.pyo", line 138, in execute
  File "bleachbit\Windows.pyo", line 218, in wu_service
  File "bleachbit\General.pyo", line 150, in run_external
  File "subprocess.pyo", line 382, in __init__
  File "subprocess.pyo", line 515, in _get_handles
  File "subprocess.pyo", line 566, in _make_inheritable
WindowsError: [Error 6] Descripteur non valide
Error in execution of <bleachbit.Command.Function instance at 0x011AEF80>
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 83, in execute
  File "bleachbit\Command.pyo", line 138, in execute
  File "bleachbit\Action.pyo", line 412, in run_process
RuntimeError: Exception in external command
Command: taskkill.exe /f /IM explorer.exe
Error: [Error 6] Descripteur non valide

**Comment by az0** [comment]
This was fixed in [BleachBit 2.0](https://www.bleachbit.org/news/bleachbit-20)
