### ISSUE TITLE
Firefox DatabaseError: no such table: moz_favicons

### ISSUE THREAD

**Issue by Stephane18** [bleachbit/bleachbit#251]
Not preventing bleachbit to run but issue when cleaning Firefox

Bleachbit version 1.17
Ubuntu 16.04.3 LTS xenial

````
Error in execution of <bleachbit.Command.Function instance at 0x7f4944153248>
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 156, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 283, in delete_mozilla_url_history
    FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/FileUtilities.py", line 348, in execute_sqlite3
    '%s: %s' % (bleachbit.decode_str(exc), path))
DatabaseError: no such table: moz_favicons: /home/stephane/.mozilla/firefox/y6x5w9kk.default/places.sqlite
````

**Comment by az0** [comment]
Key error message is `DatabaseError: no such table: moz_favicons`

Related reports
https://bugs.launchpad.net/linuxmint/+bug/1738086
https://www.bleachbit.org/forum/firefox-55
https://github.com/bleachbit/bleachbit/issues/235
