### ISSUE TITLE
Google Chrome 63: Error in execution of <bleachbit.Command.Function instance at 0x03091418>

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#258]
Clean file 0 C:\Users\username\AppData\Local\Google\Chrome\User Data\Default\History
Error in execution of <bleachbit.Command.Function instance at 0x03091418>
Delete 0 C:\Users\username\AppData\Local\Google\Chrome\User Data\Safe Browsing Cookies-journal

Google Chrome 63.0.3239.84 (Official Build) (64-bit) (cohort: Stable)
Windows 8.1 64-bit
Test build: BleachBit 1.17.566

**Comment by az0** [comment]
Ubuntu 16.04
Google Chrome 63.0.3239.84


````
Clean file 0 /home/username/.config/google-chrome/Default/History
Error in execution of <bleachbit.Command.Function instance at 0x7fc07df6ccb0>
Traceback (most recent call last):
  File "/home/bleachbit/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/bleachbit/bleachbit/bleachbit/Command.py", line 156, in execute
    self.func(self.path)
  File "/home/bleachbit/bleachbit/bleachbit/Special.py", line 165, in delete_chrome_favicons
    raise RuntimeError('%s is version %d' % (path, ver))
RuntimeError: /home/z/.config/google-chrome/Default/Favicons is version 37
Delete 0 /home/username/.config/google-chrome/Safe Browsing Cookies-journal
````
