### ISSUE TITLE
Firefox 57 Error in execution of <bleachbit.Command.Function instance at 0x031359B8>

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#261]
Delete 89.7kB C:\Users\username\AppData\Local\Mozilla\Firefox\Profiles\cyqyoo2g.default\thumbnails\ad5a4453bea49203135688a7b8db842d.png
Error in execution of <bleachbit.Command.Function instance at 0x031359B8>
Vacuum 4.9MB C:\Users\username\AppData\Roaming\Mozilla\Firefox\Profiles\cyqyoo2g.default\favicons.sqlite

Build identifier: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0

Windows 8.1 64-bit
Test build: BleachBit 1.17.566

**Comment by az0** [comment]
Not reproduced with
Ubuntu 16.04.03
Firefox/57.0

Reproduced with clean Firefox profile on Firefox 57.0.2 
Windows 10.0.16299
````
Delete 229.4kB \AppData\Roaming\Mozilla\Firefox\Profiles\foxf3zky.default\content-prefs.sqlite
Error in execution of <bleachbit.Command.Function instance at 0x0570E170>
Traceback (most recent call last):
  File "H:\bleachbit\bleachbit\Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "H:\bleachbit\bleachbit\Command.py", line 156, in execute
    self.func(self.path)
  File "H:\bleachbit\bleachbit\Special.py", line 284, in delete_mozilla_url_history
    FileUtilities.execute_sqlite3(path, cmds)
  File "H:\bleachbit\bleachbit\FileUtilities.py", line 348, in execute_sqlite3
    '%s: %s' % (bleachbit.decode_str(exc), path))
DatabaseError: no such table: moz_favicons: \AppData\Roaming\Mozilla\Firefox\Profiles\foxf3zky.default\places.sqlite
Vacuum 5MB \AppData\Roaming\Mozilla\Firefox\Profiles\foxf3zky.default\favicons.sqlite
````
