### ISSUE TITLE
"WindowsError: [Error 5] Access is denied" in free_space()

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#27]
# Symptoms

Symptom is on first startup BleachBit crashes with an error message about a log.  The log contains the following information.  

BleachBit 1.4 is affected, but not on all Windows systems.  BleachBit 1.2 is not affected.

The problem exists on systems with special drives.  Microsoft Click and Run sets up a virtual drive like this. 

```
Traceback (most recent call last):
File "bleachbit.py", line 43, in
File "bleachbit\GUI.pyo", line 40, in
File "bleachbit\Cleaner.pyo", line 40, in
File "bleachbit\Special.pyo", line 27, in
File "bleachbit\Options.pyo", line 297, in
File "bleachbit\Options.pyo", line 65, in __init__
File "bleachbit\Options.pyo", line 194, in restore
File "bleachbit\FileUtilities.pyo", line 394, in guess_overwrite_paths
File "bleachbit\FileUtilities.pyo", line 443, in same_partition
File "bleachbit\FileUtilities.pyo", line 324, in free_space
WindowsError: [Error 5] Access is denied.
```
# Solution

Try the fixed version: download BleachBit ~~1.5~~ [1.5.1 (beta)](https://bugs.launchpad.net/bleachbit/+bug/1372179/comments/6)

**Comment by az0** [comment]
Fixed in b38030113bce131eda668c32b60262bb9c08832e
