### ISSUE TITLE
ERROR: test_delete_locked_file (tests.TestWindows.WindowsTestCase)

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#276]
https://ci.appveyor.com/project/az0/bleachbit/build/1.19.587

````
======================================================================
ERROR: test_delete_locked_file (tests.TestWindows.WindowsTestCase)
Unit test for delete_locked_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\bleachbit\tests\TestWindows.py", line 91, in test_delete_locked_file
    delete_locked_file(pathname)
  File "C:\projects\bleachbit\bleachbit\Windows.py", line 142, in delete_locked_file
    raise WinError()
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect.
````

**Comment by az0** [comment]
- Error happens when automatically running all tests on AppVeyor. (It runs with admin privileges.)
- Error does not happen in AppVeyor environment over RDP when running TestWindows
- Error does not happen in AppVeyor environment over RDP when running all tests
- Error does not happen locally on Windows 10 when running all tests as admin
- Error does not happen locally on Windows 10 when running all tests as non admin

**Comment by az0** [comment]
Error does not happen in the normal automated AppVeyor  test environment when only this test is selected (in appveyor.yml)
