### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'execute' when using mozilla_url_history

### ISSUE THREAD

**Issue by am2605** [bleachbit/bleachbit#277]
Windows 10 Professional 64-bit
BleachBit 1.19 Beta

I have multiple Firefox profiles, none of which contain the word "default" which means they don't get picked up by BleachBit unless I use a custom cleaner file such as the one at https://gist.github.com/BrunoReX/5286414

On the stable version I was seeing the DatabaseError: no such table: moz_favicons as described in #251.

So I decided to give the latest Beta a try, but now I'm seeing this error (x3 - once for each of my profiles):

```
clean_operation('firefox_xml'), options = '[u'url_history']'
Error in execution of None
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 83, in execute
AttributeError: 'NoneType' object has no attribute 'execute'
Error in execution of None
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 83, in execute
AttributeError: 'NoneType' object has no attribute 'execute'
Error in execution of None
Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 83, in execute
AttributeError: 'NoneType' object has no attribute 'execute'
```

**Comment by az0** [comment]
Hmm, that error is partially generic.

Does it happen with the [vanilla Firefox cleaner](https://gist.github.com/BrunoReX/5286414) you posted or just with your version? If it happens just with your version, would you be able to post it publicly or email it to me?

**Comment by az0** [comment]
Second question: `AttributeError: ...` error started when you updated from version 1.12 stable to 1.19 beta?

**Comment by am2605** [comment]
I'm going on my memory here sorry but I think it was present in both version.  If it's important I can downgrade and try it if you like?

I've just tried on 2.0 using the vanilla Firefox cleaner which you specify above and I'm seeing it still.  This is the output in the right hand pane:

Error in execution of None
Error in execution of None
Error in execution of None

I wonder if a workaround is to put the word "default" in my profile names somewhere?

**Comment by az0** [comment]
Trying with an older version is not important at this time. If you could try it with "default," that would be helpful. If not, later I will try troubleshooting

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Please try it out, and let me know how it goes. 

Soon the fix will be published also in BleachBit 2.2 final.
