### ISSUE TITLE
Error in execution - DatabaseError: no such table: moz_favicons - firefox 58

### ISSUE THREAD

**Issue by jcpf** [bleachbit/bleachbit#281]
Linux 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
Error in execution of <bleachbit.Command.Function instance at 0x7fc728372dd0>
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 84, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 149, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 281, in delete_mozilla_url_history
    FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/FileUtilities.py", line 307, in execute_sqlite3
    '%s: %s' % (Common.decode_str(exc), path))
DatabaseError: no such table: moz_favicons: /home/xx/.mozilla/firefox/xxxxxxxx.default-xxxxxxxxxxxxx/places.sqlite
```

For security reasons added x in the profile name

**Comment by randyrandersn** [comment]
Same here on Manjaro Linux.
```
Error in execution of <bleachbit.Command.Function instance at 0x7f9f6f962d40>
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 84, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 149, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 281, in delete_mozilla_url_history
    FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/FileUtilities.py", line 307, in execute_sqlite3
    '%s: %s' % (Common.decode_str(exc), path))
DatabaseError: no such table: moz_favicons: /home/[user]/.mozilla/firefox/[profile].default/places.sqlite
```

**Comment by az0** [comment]
I could use more information, please.

1. Open  BleachBit 
2. Click **Help**
3. Click **About** 
4. Please note the version number

Then please let me know the version of BleachBit

**Comment by jcpf** [comment]
BleachBit 1.12
Ubuntu 16.04 LTS
Thanks for your work

**Comment by az0** [comment]
This was fixed a few months ago, and it looks like issue #235 . Please test with [BleachBit version 1.19](https://www.bleachbit.org/news/bleachbit-119-beta) or newer. I would appreciate a note in this ticket that you see it was fixed. If it was not fixed, please re-open the ticket.
