### ISSUE TITLE
cannot open preferences in GTK+ 3

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#314]
````
Traceback (most recent call last):
  File "/bleachbit/bleachbit/GUI.py", line 186, in cb_preferences_dialog
    pref = PreferencesDialog(self._window, self._window.cb_refresh_operations)
  File "/bleachbit/bleachbit/GuiPreferences.py", line 65, in __init__
    notebook.append_page(self.__general_page(), Gtk.Label(label=_("General")))
  File "/bleachbit/bleachbit/GuiPreferences.py", line 107, in __general_page
    swcc = Unix.start_with_computer_check
AttributeError: 'module' object has no attribute 'start_with_computer_check'
````

**Comment by az0** [comment]
Fixed in 6150a50fc130bb2f1c61cfa5d272dce9c90571d2
