### ISSUE TITLE
cannot read winapp2.ini with BOM

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#318]
Edited with Notepad on Windows 10

````
Error reading winapp2.ini cleaner 'C:\Users\x\AppData\Roaming\BleachBit\cleaners\winapp2.ini'
Traceback (most recent call last):
  File "\bleachbit\Winapp.py", line 399, in load_cleaners
    inicleaner = Winapp(pathname)
  File "\bleachbit\Winapp.py", line 150, in __init__
    self.parser.read(pathname)
  File "C:\Python27\lib\ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "C:\Python27\lib\ConfigParser.py", line 512, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
MissingSectionHeaderError: File contains no section headers.
file: C:\Users\x\AppData\Roaming\BleachBit\cleaners\winapp2.ini, line: 1
'\xef\xbb\xbf\n'
````

**Comment by az0** [comment]
For reference, fix was here by Rados
https://github.com/bleachbit/bleachbit/pull/611
