### ISSUE TITLE
__init__.expandvars fails with invalid encoding

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#327]
Seen when /tmp/ has a filename with invalid encoding and when running tests.TestCLI.CLITestCase.test_delete

Second issue is that the unit test passes

`touch $(echo -e "\x8b\x8b-bad")`

````
path(/tmp/DeepScanTestCaseucSY1z/äöüßÄÖÜ_dir/äöüßÄÖÜ��bad) type = <type 'str'>
Error: system.tmp: Command to delete /tmp/DeepScanTestCaseucSY1z/äöüßÄÖÜ_dir/äöüßÄÖÜ��bad
Traceback (most recent call last):
  File "bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "tests/TestCLI.py", line 137, in dummy_delete
    self.assertExists(path)
  File "tests/common.py", line 76, in assertExists
    path = expandvars(path)
  File "bleachbit/__init__.py", line 108, in expandvars
    final = var.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
````

**Comment by az0** [comment]
I can still reproduce on Git master branch (63baa352c894e730758622e80d097b18be416a5f) by running these commands

```
touch /tmp/$(echo -e "\x8b\x8b-bad")
python -m unittest tests.TestCLI.CLITestCase.test_delete
```
Error
```
Error: system.tmp: Command to delete /tmp/��-bad
Traceback (most recent call last):
  File "bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "tests/TestCLI.py", line 132, in dummy_delete
    self.assertExists(path)
  File "tests/common.py", line 77, in assertExists
    path = expandvars(path)
  File "bleachbit/__init__.py", line 103, in expandvars
    final = var.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 5: invalid start byte
```

System is Ubuntu 19.04 with Python 2.7.16

**Comment by az0** [comment]
Note to self: Rados contract
