### ISSUE TITLE
GTK+ 3 GUI is not usable on Windows

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#331]
- The menus (file, help, etc.) are missing
- Unable to access functions in the menus (such as preferences)
- All buttons (clean, preview, minimize, maximize, close) are missing icons
- Errors seen in console on startup
````
C:\Program Files (x86)\BleachBit>bleachbit_console.exe
Traceback (most recent call last):
  File "bleachbit\GUI.pyo", line 219, in do_startup
  File "bleachbit\GUI.pyo", line 96, in build_app_menu
GLib.Error: g-file-error-quark: Failed to open file â?oC:\Program Files (x86)\BleachBit\data\app-menu.uiâ??: No such file or directory (4)

(bleachbit_console.exe:1428): Gtk-WARNING **: Could not find the icon 'edit-find-ltr'. The 'hicolor' theme
was not found either, perhaps you need to install it.
You can get a copy from:
        http://icon-theme.freedesktop.org/releases

(bleachbit_console.exe:1428): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Icon 'image-missing' not present in theme Adwaita

(bleachbit_console.exe:1428): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Icon 'image-missing' not present in theme Adwaita
C:\Program Files (x86)\BleachBit\library.zip\bleachbit\GUI.py:902: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
````
- Error repeats in console: 
````
(bleachbit_console.exe:1428): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Icon 'image-missing' not present in theme Adwaita
````

See screenshot
![2018-04 gtk3 on windows 10 - not usable](https://user-images.githubusercontent.com/933680/38910135-2f108d7c-4285-11e8-9d78-e37f0d99d0a7.png)

**Comment by az0** [comment]
The Appveyor build works works much better now: menus work, preferenes works, buttons have icons, and cleaning works, so I am closing. I'll open new tickets for other issues.


> Git revision 0ca3b347
> GTK version 3.18.9
> platform.win32_ver[1]() = 10.0.17763
> platform.platform = Windows-10-10.0.17763
> platform.version = 10.0.17763

**Comment by az0** [comment]
Portable mode works fine, but the installed version is broken. Symptoms are the same except the log stops after the app-menu.ui
