### ISSUE TITLE
--shred command line does not work with GTK+ 3 GUI

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#334]
````
$ python bleachbit.py  --shred --gui COPYING 

Traceback (most recent call last):
  File "bleachbit.py", line 43, in <module>
    bleachbit.CLI.process_cmd_line()
  File "/bleachbit/bleachbit/CLI.py", line 215, in process_cmd_line
    app = bleachbit.GUI.Bleachbit(uac=not options.no_uac, shred_paths=args, exit=options.exit)
  File "/bleachbit/bleachbit/GUI.py", line 70, in __init__
    self.shred_paths(shred_paths)
AttributeError: 'Bleachbit' object has no attribute 'shred_paths'
````

Seen in Git commit ede855c883126c9b8ec7cf3d5fd5676e0a271498. 

It is basically the same on Windows 10 and Ubuntu 16.04

**Comment by az0** [comment]
I confirmed this is still a problem for branch gtk3 as of commit 3a3d923
