### ISSUE TITLE
button to update does not work (GTK+ 3)

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#335]
When `update_dialog()` gets valid URLs, it does not pass them to `open_url()` because `open_url()` refers the URL as `False`.

Seen in ede855c883126c9b8ec7cf3d5fd5676e0a271498

**Comment by az0** [comment]
I confirmed this is still a problem for branch gtk3 as of commit 3a3d923

````
Traceback (most recent call last):
  File "/bleachbit/bleachbit/Update.py", line 142, in <lambda>
    'clicked', lambda dummy: open_url(url, parent, False))
  File "/bleachbit/bleachbit/GuiBasic.py", line 171, in open_url
    ret = re.search('^http(s)?://([a-z.]+)', url)
  File "/usr/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
````
