### ISSUE TITLE
Better error handling when using "system.free_disk_space"

### ISSUE THREAD

**Issue by ruzickap** [bleachbit/bleachbit#381]
Hello.

Would it be possible to handle the disk full error nicely than how it looks right now when using the `system.free_disk_space`:

```
 C:\Users\vagrant>\BleachBit-Portable\bleachbit_console.exe --clean system.free_disk_space
 info: exception on f.flush()
 Traceback (most recent call last):
   File "bleachbit\FileUtilities.pyo", line 806, in wipe_path
 IOError: [Errno 28] No space left on device
 Overwrite free disk space C:\Users\vagrant\AppData\Local\Temp 0
 Disk space recovered: 0
 wrote 6 files and 36009627653 bytes in 194 seconds at 185.55 MB/s
 Files deleted: 0
 Special operations: 1
```

I do not like the python trace, because it may be confusing - looks like some serious problem.

I would prefer some message saying the "disk fill operation" was completed:

```
 C:\Users\vagrant>\BleachBit-Portable\bleachbit_console.exe --clean system.free_disk_space
 Disk was successfully wiped...
 Overwrite free disk space C:\Users\vagrant\AppData\Local\Temp 0
 Disk space recovered: 0
 wrote 6 files and 36009627653 bytes in 194 seconds at 185.55 MB/s
 Files deleted: 0
 Special operations: 1
```

Thank you

PetrR

**Comment by az0** [comment]
The fix was published in [BleachBit 2.1 beta](https://www.bleachbit.org/news/bleachbit-21-beta). Please try it out, and let me know how it goes. 

Soon the fix will be published also in BleachBit 2.2 final.

**Comment by ruzickap** [comment]
Hello.

I tried the BleachBit 2.1 beta - the "error" output is better, but I can still see this "traceback error" - which should be "hidden" from users:

```
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 829, in wipe_path
IOError: [Errno 28] No space left on device
```

Here is a full log:

```
C:\Program Files (x86)\BleachBit>bleachbit_console.exe --clean system.free_disk_space
makedirs(C:\Users\vagrant\AppData\Roaming\BleachBit)
automatically preserving language 'en'
clean_operation('system'), options = '[]'
wipe_path('C:\Users\vagrant\AppData\Local\Temp\1')
creating new, temporary file to wipe path
info: exception on f.flush()
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 829, in wipe_path
IOError: [Errno 28] No space left on device
creating new, temporary file to wipe path
creating new, temporary file to wipe path
creating new, temporary file to wipe path
creating new, temporary file to wipe path
creating new, temporary file to wipe path
creating new, temporary file to wipe path
wrote 6 files and 40759996421 bytes in 318 seconds at 127.96 MB/s
Overwrite free disk space C:\Users\vagrant\AppData\Local\Temp\1 0
Disk space recovered: 0
Files deleted: 0
Special operations: 1


C:\Program Files (x86)\BleachBit>bleachbit_console.exe --version

BleachBit version 2.1
Copyright (C) 2008-2018 Andrew Ziem.  All rights reserved.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

Thanks for looking at it...

**Comment by M-Pixel** [comment]
For unexpected errors, showing traceback is good for getting usable bug reports, but I agree that for something like "out of disk space" it's more of a distraction than a help.

**Comment by ruzickap** [comment]
Sure... 
I agree that traces are fine, but `bleachbit_console.exe --clean system.free_disk_space` did it's job properly - so I do not expect to see some "error like" messages or traces. 

It may just scare the users.

If there is some real problem - then yes - you should get as much details about problem as possible, but not in the case when the program is working as expected...
