### ISSUE TITLE
Debian Stretch: BleachBit causing error since updating Firefox to 60.0 ESR

### ISSUE THREAD

**Issue by EarthlingX** [bleachbit/bleachbit#401]
I am running Debian 9 (Stretch).

With previous Firefox versions BleachBit has worked completely fine. However, since updating Firefox to Firefox Quantum 60.0 ESR now Bleachbit is causing the following error:

```
Error in execution of <bleachbit.Command.Function instance at 0x7f939785e710>
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 84, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 149, in execute
    self.func(self.path)
  File "/usr/share/bleachbit/bleachbit/Special.py", line 281, in delete_mozilla_url_history
    FileUtilities.execute_sqlite3(path, cmds)
  File "/usr/share/bleachbit/bleachbit/FileUtilities.py", line 307, in execute_sqlite3
    '%s: %s' % (Common.decode_str(exc), path))
DatabaseError: no such table: moz_favicons: /home/user/.mozilla/firefox/kztmefbe.default/places.sqlite
```

![screenshot](https://user-images.githubusercontent.com/38689554/47714707-86569a00-dc35-11e8-89fa-959be60e460a.png)

Maybe you can have a look at that one?

Thanks a lot in advance! :)

With best regards!
Daniel

**Comment by EarthlingX** [comment]
@az0: I am using BleachBit version 1.12 (from the official Debian Stable-repositories).

So this version is already replaced by a newer one? Maybe you could push the new one into the stable repos? That would be great! :+1:
