### ISSUE TITLE
Unknown Issue

### ISSUE THREAD

**Issue by 2635599** [bleachbit/bleachbit#588]
i get the following when running bleach as root. 

```
Error in execution of <bleachbit.Command.Function instance at 0x7f3f26319e60>
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/bleachbit/Command.py", line 138, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/bleachbit/Unix.py", line 610, in apt_autoremove
    raise RuntimeError("Error calling '%s':\n%s" % (' '.join(e.cmd), e.output))
RuntimeError: Error calling 'apt-get --yes autoremove':
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  bridge-utils libboost-log1.67.0 libboost-program-options1.67.0
  libboost-regex1.67.0 liblxc-common liblxc1 libpam-cgfs libsdl2-image-2.0-0
  lxc lxc-utils lxcfs uidmap
0 upgraded, 0 newly installed, 12 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 14.0 MB disk space will be freed.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 352789 files and directories currently installed.)
Removing lxc (3.0.3-0ubuntu1) ...
Removing lxc-utils (3.0.3-0ubuntu1) ...
Removing lxc dnsmasq configuration
Removing bridge-utils (1.6-2ubuntu1) ...
Removing libboost-log1.67.0 (1.67.0-13) ...
Removing libboost-program-options1.67.0:amd64 (1.67.0-13) ...
Removing libboost-regex1.67.0:amd64 (1.67.0-13) ...
Removing libpam-cgfs (3.0.3-0ubuntu1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Removing libsdl2-image-2.0-0:amd64 (2.0.4+dfsg1-1) ...
Removing lxcfs (3.0.3-0ubuntu1) ...
Removing uidmap (1:4.5-1.1ubuntu2) ...
Removing liblxc-common (3.0.3-0ubuntu1) ...
Removing liblxc1 (3.0.3-0ubuntu1) ...
Setting up anbox-modules-dkms (13~disco1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
Removing old anbox-1 DKMS files...

-------- Uninstall Beginning --------
Module:  anbox
Version: 1
Kernel:  5.0.0-20-generic (x86_64)
-------------------------------------

Status: Before uninstall, this module version was ACTIVE on this kernel.

ashmem_linux.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.0.0-20-generic/updates/dkms/
rmdir: failed to remove 'updates/dkms': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.


binder_linux.ko:
 - Uninstallation
   - Deleting from: /lib/modules/5.0.0-20-generic/updates/dkms/
rmdir: failed to remove 'updates/dkms': Directory not empty
 - Original module
   - No original module was found for this module on this kernel.
   - Use the dkms install command to reinstall any previous module version.

depmod...

DKMS: uninstall completed.

------------------------------
Deleting module version: 1
completely from the DKMS tree.
------------------------------
Done.
Loading new anbox-1 DKMS files...
Building for 5.0.0-20-generic 5.1.7-050107-generic
Building initial module for 5.0.0-20-generic
Secure Boot not enabled on this system.
Done.

ashmem_linux.ko:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/5.0.0-20-generic/updates/dkms/

binder_linux.ko:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/5.0.0-20-generic/updates/dkms/

depmod...

DKMS: install completed.
Building initial module for 5.1.7-050107-generic
ERROR (dkms apport): kernel package linux-headers-5.1.7-050107-generic is not supported
Error! Bad return status for module build on kernel: 5.1.7-050107-generic (x86_64)
Consult /var/lib/dkms/anbox/1/build/make.log for more information.
dpkg: error processing package anbox-modules-dkms (--configure):
 installed anbox-modules-dkms package post-installation script subprocess returned error exit status 10
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.29-0ubuntu2) ...
Errors were encountered while processing:
 anbox-modules-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
running kubuntu 19.04 64 bit, kernel 5.0.0.20

**Comment by az0** [comment]
There is some issue uninstalling anbox-modules-dkms

Has this happened more than once? What if you run this command from the command line?

`sudo apt-get --yes autoremove`

**Comment by 2635599** [comment]
a friend figyred out a command for removing the module using a different command. this is the first time i'm awate of, but anbox does seem to have it's issues. installed under kde neon and never fully launched. had graphic remnants on the screen. install it here in kubuntu and it sits saying starting and after about 20 seconds closes out. right now every bit of andox is off my system.  i'm not sure what's going on with it but in my case seems to just not want to work.

**Comment by 2635599** [comment]
ok sorry i really didn't pay attention last night. thought this was the anbox issue i  posted on their git page. so i thought they were referring to error messages i was getting for anbox in komsole every time i p;ut in a update command. that said just ran bleachbit and finished without error.  so looks like manually purging anbox did the trick. thanks for taking the time to look at this.
