### ISSUE TITLE
v.2.2 portable on Win 7Pro x64: ImportError: DLL load failed

### ISSUE THREAD

**Issue by caganer** [bleachbit/bleachbit#589]
BleachBit-2.2-portable.zip
MD5: 274661b26b8776db7da90abed4c6b32b

bleachbit.exe.log says

Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.

**Comment by caganer** [comment]
Edit: in case it is not self-explanatory already from the actual log copied above, the error stated precluded launch so nothing was "done" before the error occurred, other than running the executable.

**Comment by az0** [comment]
That's the right md5 sum.  Some of BleachBit is working, but 

Which antivirus/security software do you use? For testing purposes, could you temporarily disable it in case it is blocking the DLL load?

**Comment by caganer** [comment]
No real time antivirus is installed on this Windows 7 Pro x64 laptop except for the bundled Windows Defender. Occasionally I manually run MalwareBytes AdwCleaner v7.4.0 and ClamWin v.0.99.4 but afaik neither is a permanently memory resident application.
To diagnose this issue I first added bleachbit.exe to Excluded Files and Folders in Windows Defender Options but it still would not run.  
I then disabled Windows Defender Real-Time Protection but same result. 
Last, I added the instal folder for the executable to Windows Defender's Excluded Files and Folders  but same result.

The log file as last updated by the executable is as follows:

Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
  File "bleachbit.py", line 44, in <module>
  File "bleachbit\__init__.pyo", line 353, in <module>
  File "bleachbit\Windows.pyo", line 59, in <module>
  File "win32gui.pyo", line 12, in <module>
  File "win32gui.pyo", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.

**Comment by az0** [comment]
@caganer  

1. Separately from BleachBit, do you have Python installed on your system? There could be a conflict with a DLL that BleachBit provides.

2. For troubleshooting, could you please try a recent build from https://ci.bleachbit.org/ ?

**Comment by caganer** [comment]
Python3 is installed on that system and also on a Windows 7 x64 Home Premium laptop.
The latter has Bleachbit 2.0 Portable on it which always runs fine (as does v.2.0 on the Win7 Pro box - I've since removed portable v.2.2).

I downloaded and tried BleachBit-2.3-portable on the Win7 HP laptop which actually did present the GUI but the log reads:

"Error when setting the default drives to shred.
Traceback (most recent call last):
  File "bleachbit\Options.pyo", line 248, in restore
  File "bleachbit\FileUtilities.pyo", line 488, in guess_overwrite_paths
  File "bleachbit\FileUtilities.pyo", line 543, in same_partition
  File "bleachbit\FileUtilities.pyo", line 408, in free_space
  File "psutil\__init__.pyo", line 141, in <module>
  File "psutil\_pswindows.pyo", line 17, in <module>
  File "psutil\_psutil_windows.pyo", line 12, in <module>
  File "psutil\_psutil_windows.pyo", line 10, in __load
ImportError: DLL load failed: The specified procedure could not be found."

(Incidentally, that new dark interface is much harder to read than in v2.0 and controls and any menu entries are hard to locate).

On both machines Bleachbit portable (v2.0 and when tested, v2.2, v.2.3) is installed in a directory not mentioned in the path. On the Home Premium machine (no chance yet to check the Pro machine but I guess in this regard it is the same) the path environment variable does include

C:\Program Files (x86)\Python3\Scripts\;C:\Program Files (x86)\Python3\

- but that doesn't stop portable version 2.0 working fine.

**Comment by az0** [comment]
I put in a fix for [build 2.3.1212](https://ci.bleachbit.org/?prefix=dl/2.3.1212/) to prevent a DLL conflict. Please try it, and let me know how it goes.

**Comment by az0** [comment]
I haven't heard back in 15 days, so I will close it. If you have the same DLL error, reopen this ticket. If you test it and it works, please add a comment to this ticket.

**Comment by az0** [comment]
You could test the fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta). Let me know how it goes
