### ISSUE TITLE
crash when previewing on Windows when username has Unicode characters

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#602]
This happened when the username included Unicode characters.

System: Windows 10.0.18362.145
Git revision: 23decebcf33192b52b4acee43c0d5be00f880e48

```
Exception while running operation 'internet_explorer': ''ascii' codec can't encode character u'\xf0' in position 12: ordinal not in range(128)'
Traceback (most recent call last):
  File "B:\bleachbit\Worker.py", line 351, in run_operations
    for dummy in self.clean_operation(operation):
  File "B:\bleachbit\Worker.py", line 161, in clean_operation
    for ret in self.execute(cmd, '%s.%s' % (operation, option_id)):
  File "B:\bleachbit\Worker.py", line 126, in execute
    path = path.decode('utf8', 'replace')  # for invalid encoding
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf0' in position 12: ordinal not in range(128)
```

**Comment by az0** [comment]
I tested revision 54e0f8e6c417de9cb57033732d34e5eece0b2741 with a username tPython 3.4 on Windows 10, and it worked fine with a  username with a Unicode character. I tried basic operations,
