### ISSUE TITLE
app-menu not found on CentOS 7

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#634]
```
$ bleachbit
scandir is not available, so falling back to slower os.walk()
Automatically preserving language en.
Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 250, in do_startup
    self.build_app_menu()
  File "/usr/share/bleachbit/GUI.py", line 98, in build_app_menu
    builder.add_from_file(bleachbit.app_menu_filename)
GLib.Error: g-file-error-quark: Failed to open file “/usr/share/data/app-menu.ui”: No such file or directory (4)
Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 284, in do_activate
    application=self, title=APP_NAME, auto_exit=self._auto_exit)
  File "/usr/share/bleachbit/GUI.py", line 466, in __init__
    self.populate_window()
  File "/usr/share/bleachbit/GUI.py", line 972, in populate_window
    self.headerbar = self.create_headerbar()
  File "/usr/share/bleachbit/GUI.py", line 915, in create_headerbar
    builder.add_from_file(bleachbit.app_menu_filename)
GLib.Error: g-file-error-quark: Failed to open file “/usr/share/data/app-menu.ui”: No such file or directory (4)
```

**Comment by az0** [comment]
Fixed in 049f8f2e
