### ISSUE TITLE
ImportError with make chaff on CentOS 7

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#635]
```
$ bleachbit
scandir is not available, so falling back to slower os.walk()
Traceback (most recent call last):
  File "/usr/share/bleachbit/GUI.py", line 125, in cb_make_chaff
    from bleachbit.GuiChaff import ChaffDialog
  File "/usr/share/bleachbit/GuiChaff.py", line 30, in <module>
    from bleachbit.Chaff import download_models, generate_emails, generate_2600, have_models
  File "/usr/share/bleachbit/Chaff.py", line 34, in <module>
    from . import markovify
ImportError: cannot import name markovify
```
Git revision 049f8f2e

**Comment by az0** [comment]
Fixed
