### ISSUE TITLE
Arch Linux - Bleachbit (root) error messages.

### ISSUE THREAD

**Issue by Davetheraveuk** [bleachbit/bleachbit#642]
Hi, I have run Bleachbit as root and I got the following error messages (I am not a developer):

```
Error: system.custom: Command to delete /home/dave/.cache
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 270, in delete
    logger.info(_("Directory is not empty: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /var/cache
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 270, in delete
    logger.info(_("Directory is not empty: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /tmp
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 265, in delete
    os.rmdir(delpath)
OSError: [Errno 16] Device or resource busy: '/tmp'
Error: system.custom: Command to delete /tmp/.com.vivaldi.Vivaldi.tMkAZx/SingletonSocket
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 303, in delete
    logger.info(_("Special file type cannot be deleted: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /tmp/.ICE-unix/845
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 303, in delete
    logger.info(_("Special file type cannot be deleted: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /tmp/.X11-unix/X0
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 303, in delete
    logger.info(_("Special file type cannot be deleted: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /tmp/.com.vivaldi.Vivaldi.tMkAZx
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 270, in delete
    logger.info(_("Directory is not empty: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /tmp/.ICE-unix
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 270, in delete
    logger.info(_("Directory is not empty: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /tmp/.X11-unix
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 270, in delete
    logger.info(_("Directory is not empty: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /tmp/sddm-:0-lgJxVT
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 303, in delete
    logger.info(_("Special file type cannot be deleted: %s"), path)
NameError: global name '_' is not defined
Error: system.custom: Command to delete /tmp/sddm-auth5e5df04d-8dd3-4edf-8a89-d9703f40601e
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 303, in delete
    logger.info(_("Special file type cannot be deleted: %s"), path)
NameError: global name '_' is not defined

```
The "resource busy" message I understand. 
But the rest - scratchy head time. :)

Thanks, Dave.

**Comment by az0** [comment]
Most of these are the same `NameError` which was reported and fixed earlier here: https://github.com/bleachbit/bleachbit/issues/508

The "Device or resource busy" error looks like the one that was fixed here: https://github.com/bleachbit/bleachbit/issues/573

Are you able to run [BleachBit from source](https://docs.bleachbit.org/dev/running-from-source-code.html) to confirm these are fixed on your system? Otherwise, you can wait until the next release. I'm close to releasing 2.3 beta, but I personally don't provide packages for Arch.

**Comment by az0** [comment]
If BleachBit [2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta) fixes it, please add a comment here to confirm it was fixed. If the problem persists, please open this ticket.
