### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#643]
```
Downloading https://sourceforge.net/projects/bleachbit/files/chaff/clinton_subject_model.json.bz2/download to C:\temp\sig\BleachBit-2.3-portable\BleachBit-Portable\clinton_subject_model.json.bz2
Traceback (most recent call last):
  File "bleachbit\GuiChaff.pyo", line 160, in on_make_files
  File "bleachbit\GuiChaff.pyo", line 140, in download_models_dialog
  File "bleachbit\GuiChaff.pyo", line 130, in download_models_gui
  File "bleachbit\Chaff.pyo", line 173, in download_models
  File "bleachbit\Chaff.pyo", line 112, in download_url_to_fn
ImportError: No module named requests
```
Git revision 7f3605d2
Windows 10
BleachBit in portable mode

**Comment by az0** [comment]
After adding requests earlier in the appveyor.xml, I get

```
Automatically preserving language en.
Downloading https://sourceforge.net/projects/bleachbit/files/chaff/clinton_subject_model.json.bz2/download to C:\Users\username\Downloads\BleachBit-2.3-portable (1)\BleachBit-Portable\clinton_subject_model.json.bz2
Traceback (most recent call last):
  File "bleachbit\GuiChaff.pyo", line 160, in on_make_files
  File "bleachbit\GuiChaff.pyo", line 140, in download_models_dialog
  File "bleachbit\GuiChaff.pyo", line 130, in download_models_gui
  File "bleachbit\Chaff.pyo", line 173, in download_models
  File "bleachbit\Chaff.pyo", line 138, in download_url_to_fn
  File "requests\sessions.pyo", line 546, in get
  File "requests\sessions.pyo", line 533, in request
  File "requests\sessions.pyo", line 646, in send
  File "requests\adapters.pyo", line 416, in send
  File "requests\adapters.pyo", line 228, in cert_verify
IOError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\username\Downloads\BleachBit-2.3-portable (1)\BleachBit-Portable\library.zip\certifi\cacert.pem
```
