### ISSUE TITLE
TypeError with notify

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#717]
mkhon's GUI test branch

There was a long preview, which triggered the notification.

2f09f47356143fba36bd61a8e3ed91e1b5196568

$ python -m unittest tests.TestGUI
/tmp/GUITestCase8ljnu9
....Traceback (most recent call last):
  File "bleachbit/Worker.py", line 317, in run
    self.ui.worker_done(self, self.really_delete)
  File "bleachbit/GUI.py", line 720, in worker_done
    notify.set_hint("desktop-entry", "bleachbit")
TypeError: argument value: Expected GLib.Variant, but got str
.

**Comment by az0** [comment]
I presume this was fixed with da98880cac1a6ea0741e4996c64d56edc46441a4
