### ISSUE TITLE
SyntaxError: invalid syntax with class ActionProvider(metaclass=PluginMount)

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#757]
```
$ python bleachbit.py 
Traceback (most recent call last):
  File "/tmp/bleachbit/bleachbit/GUI.py", line 739, in cb_refresh_operations
    from bleachbit import RecognizeCleanerML
  File "/tmp/bleachbit/bleachbit/RecognizeCleanerML.py", line 27, in <module>
    from bleachbit.CleanerML import list_cleanerml_files
  File "/tmp/bleachbit/bleachbit/CleanerML.py", line 26, in <module>
    from bleachbit.Action import ActionProvider
  File "/tmp/bleachbit/bleachbit/Action.py", line 104
    class ActionProvider(metaclass=PluginMount):
                                  ^
SyntaxError: invalid syntax

$ python -V
Python 2.7.16

$ git status
On branch python3
Your branch is up to date with 'origin/python3'.

nothing to commit, working tree clean

$ git remote -v
origin	git@github.com:mkhon/bleachbit.git (fetch)
origin	git@github.com:mkhon/bleachbit.git (push)

$ git rev-parse HEAD
eeaa947a2ac9eb33419444bb71032853bc5c559d

$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
```

**Comment by mkhon** [comment]
python3 branch is not compatible with python2. This one is invalid (not a bug).

**Comment by az0** [comment]
You're right
