### ISSUE TITLE
Unable to add a custom folder to be deleted

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#784]
```
BleachBit version 3.9.0
Build number 1513
platform.win32_ver[1]() = 6.2.9200
platform.platform = Windows-8-6.2.9200-SP0
platform.version = 6.2.9200
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
```
```
Traceback (most recent call last):
File "C:\projects\bleachbit\bleachbit\GuiPreferences.py", line 382, in add_custom_folder_cb
File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 976, in append
File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 967, in _do_insert
File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 875, in _convert_row
File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 893, in _convert_value
File "C:\Python34\lib\site-packages\gi\overrides\GObject.py", line 218, in __init__
File "C:\Python34\lib\site-packages\gi\overrides\GObject.py", line 274, in set_value
```

**Comment by az0** [comment]
Thanks for the detailed bug report. I'll check it to it

**Comment by ediowar** [comment]
And unable to add folder to whitelist
```
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\GuiPreferences.py", line 339, in add_whitelist_folder_cb
  File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 976, in append
  File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 967, in _do_insert
  File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 875, in _convert_row
  File "C:\Python34\lib\site-packages\gi\overrides\Gtk.py", line 893, in _convert_value
  File "C:\Python34\lib\site-packages\gi\overrides\GObject.py", line 218, in __init__
  File "C:\Python34\lib\site-packages\gi\overrides\GObject.py", line 274, in set_value
```

**Comment by az0** [comment]
I could not reproduce on Ubuntu 19.10 with BleachBit 3.9.0 (3dd33e91e72127deb69e94ec424d48757d07cd85). I added a custom folder, and then it deleted fine. Later, I'll do more testing

**Comment by az0** [comment]
I reproduced with build 1511  (Python 3) on Windows 10. It has this line

```
ValueError: Expected string but got b'C:\\Users\\x\\Downloads\\BleachBit-3.1.0.1500-portable'<class 'bytes'>
```

**Comment by az0** [comment]
Please try build 3.9.0.1533

**Comment by ediowar** [comment]
I tried, there is no bug.
