### ISSUE TITLE
SQLite update broke AppVeyor build

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#786]
https://ci.appveyor.com/project/az0/bleachbit/builds/30898242#L685

```
2020-02-19 04:00:36 - INFO - Checking bleachbit_console.exe starts
C:\projects\bleachbit\dist\library.zip\win_unicode_console\__init__.py:31: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == 'cp1252', readline hook consumer may assume they are the same
Traceback (most recent call last):
  File "bleachbit_console.py", line 47, in <module>
  File "C:\projects\bleachbit\bleachbit\__init__.py", line 282, in <module>
    from bleachbit import Windows
  File "C:\projects\bleachbit\bleachbit\Windows.py", line 41, in <module>
    from bleachbit import Command, FileUtilities, General
  File "C:\projects\bleachbit\bleachbit\Command.py", line 32, in <module>
    from sqlite3 import DatabaseError
  File "C:\Python34\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Python34\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: Invalid access to memory location.) 'C:\\projects\\bleachbit\\dist\\_sqlite3.pyd'
Traceback (most recent call last):
  File "C:\Python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\projects\bleachbit\windows\setup_py2exe.py", line 537, in <module>
    shrink()
  File "C:\projects\bleachbit\windows\setup_py2exe.py", line 452, in shrink
    assert_execute_console()
  File "C:\projects\bleachbit\windows\setup_py2exe.py", line 128, in assert_execute_console
    'Success')
  File "C:\projects\bleachbit\windows\setup_py2exe.py", line 118, in assert_execute
    actual_output = subprocess.check_output(args).decode(setup_encoding)
  File "C:\Python34\lib\subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['dist\\bleachbit_console.exe', '--gui', '--exit', '--no-uac']' returned non-zero exit status 255
```

**Comment by az0** [comment]
Resolved by fixing UPX path. In other words, when UPX compression didn't work, it gave this SQLite error
