### ISSUE TITLE
configparser.DuplicateOptionError

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#812]
Ubuntu 16.04.6 LTS, BleachBit version 3.9.0
Running from source code, Git revision https://github.com/bleachbit/bleachbit/commit/b33e863f27ecceeb82c1b6f630764498a519361a
```
clean_operation('vlc'), options = '['mru']'
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=General, parameter=filedialog-path 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 232, in clean_ini
    config.read_file(fp)
  File "/usr/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/dzmitry/.config/vlc/vlc-qt-interface.conf' [line 16]: option 'bgsize' in section 'MainWindow' already exists
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=RecentsMRL, parameter=None 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 232, in clean_ini
    config.read_file(fp)
  File "/usr/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/dzmitry/.config/vlc/vlc-qt-interface.conf' [line 16]: option 'bgsize' in section 'MainWindow' already exists
Error: vlc.mru: Command to clean .ini path=/home/dzmitry/.config/vlc/vlc-qt-interface.conf, section=OpenDialog, parameter=netMRL 
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 210, in execute
    FileUtilities.clean_ini(self.path, self.section, self.parameter)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/FileUtilities.py", line 232, in clean_ini
    config.read_file(fp)
  File "/usr/lib/python3.5/configparser.py", line 715, in read_file
    self._read(f, source)
  File "/usr/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/home/dzmitry/.config/vlc/vlc-qt-interface.conf' [line 16]: option 'bgsize' in section 'MainWindow' already exists

Disk space recovered: 0
Files deleted: 0
Errors: 3
elapsed time: 0 seconds
```

**Comment by az0** [comment]
The root cause is ConfigParser is case insensitive. After rewriting a file, it makes the entries lowercase. Then, VLC adds the mixed case key. Finally, BleachBit sees there are two keys (varying by case). The solution is to be case sensitive.

**Comment by mkhon** [comment]
This should be enough:

```
    config = bleachbit.RawConfigParser()
    config.optionxform = str
```

**Comment by az0** [comment]
@mkhon 
Yes, I think that could be the solution

**Comment by mkhon** [comment]
Reproduction scenario:
- run VLC, close VLC
- run bleachbit, clean "VLC media player / Most recently used" - this transforms "bgSize" key to "bgsize" in ~/.config/vlc/vlc-qt-interface.conf
- run VLC for the second time, close VLC - VLC preserves "bgsize" key and adds a new on "bgSize"
- run "VLC media player / Most recently used" cleaner again
