### ISSUE TITLE
application does not start unless bleachbit.exe compressed by UPX

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#827]
Antivirus software sometimes flags BleachBit as malware using heuristics, and two flags are (1) UPX compression and (2) Python. Compressing bleachbit.exe gains relatively little space, but decompressing it helps much with false positives in antivirus software.

However, after running `upx -d bleachbit.exe`, BleachBIt will not start. When I tested BleachBit 3.9.0 beta, there was no obvious error, but there was an error logged in the Windows Event Viewer.

This bug is to make it so that bleachbit.exe can be uncompressed. The other code (pyd/dll files) will still be compressed with UPX.

See also issue https://github.com/bleachbit/bleachbit/issues/771

**Comment by ediowar** [comment]
> This bug is to make it so that bleachbit.exe can be uncompressed.

So this is bug of upx?

**Comment by az0** [comment]
> So this is bug of upx? https://github.com/upx/upx/issues?q=Event+Viewer+

No, I think it is not. A while ago I tried a build without UPX compression in the first place, and it wouldn't start either.

**Comment by ediowar** [comment]
I remember that, but in this case the issue title is inappropriate.

**Comment by az0** [comment]
> I remember that, but in this case the issue title is inappropriate.

How about "application does not start unless bleachbit.exe compressed by UPX"?

**Comment by ediowar** [comment]
Good.

**Comment by ediowar** [comment]
And what about option 

> **--exact**: when compressing, require to be able to get a byte-identical file after decompression with option -d. [NOTE: this is work in progress and is not supported for all formats yet. If you do care, as a workaround you can compress and then decompress your program a first time - any further compress-decompress steps should then yield byte-identical results as compared to the first decompressed version.]

upx-3.96-win64\upx.html

**Comment by mkhon** [comment]
--exact does not work:

```
ERROR - upx: dist\bleachbit.exe: CantPackException: option '--exact' does not work with this file
upx: dist\bleachbit_console.exe: CantPackException: option '--exact' does not work with this file
upx: dist\gi.overrides._gi_gst.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\gi._gi.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\gi._gi_cairo.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\libatk-1.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libcairo-gobject-2.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libepoxy-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libffi-6.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libfontconfig-1.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libfreetype-6.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgailutil-3-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgdk-3-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgdk_pixbuf-2.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgio-2.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgirepository-1.0-1.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libglib-2.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgmodule-2.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgobject-2.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgthread-2.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libgtk-3-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libharfbuzz-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libharfbuzz-gobject-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libharfbuzz-icu-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libintl-8.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libjasper-1.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libjpeg-8.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libnotify-4.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libpango-1.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libpangocairo-1.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libpangoft2-1.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libpangowin32-1.0-0.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libpng16-16.dll: CantPackException: option '--exact' does not work with this file
upx: dist\librsvg-2-2.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libtiff-5.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libwebp-5.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libwinpthread-1.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libxmlxpat.dll: CantPackException: option '--exact' does not work with this file
upx: dist\libzzz.dll: CantPackException: option '--exact' does not work with this file
upx: dist\msvcr100.dll: CantPackException: option '--exact' does not work with this file
upx: dist\psutil._psutil_windows.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\pyexpat.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\python34.dll: CantPackException: option '--exact' does not work with this file
upx: dist\pythoncom34.dll: CantPackException: option '--exact' does not work with this file
upx: dist\pywintypes34.dll: CantPackException: option '--exact' does not work with this file
upx: dist\select.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\sqlite3.dll: CantPackException: option '--exact' does not work with this file
upx: dist\unicodedata.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\win32api.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\win32clipboard.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\win32com.shell.shell.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\win32file.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\win32gui.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\win32process.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\win32service.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_bz2.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_ctypes.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_decimal.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_elementtree.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_hashlib.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_lzma.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_scandir.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_socket.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_sqlite3.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\_ssl.pyd: CantPackException: option '--exact' does not work with this file
upx: dist\lib\gtk-3.0\3.0.0\theming-engines\libunico.dll: CantPackException: option '--exact' does not work with this file
```

But if I don't have upx/upx.exe (no UPX compression) the executable works properly

**Comment by ediowar** [comment]
> But if I don't have upx/upx.exe (no UPX compression) the executable works properly

On which version of Windows?

**Comment by az0** [comment]
@ediowar 

You suggested some compression options, but I am trying not compress `bleachbit.exe` at all with UPX, so the antivirus scanners will relax.


@mkhon  
> But if I don't have upx/upx.exe (no UPX compression) the executable works properly

I recently did a test build with no UPX compression on any file. This was not compression followed by decompression. There was no compression in the first place.

The problem was the application would not start. See [3.9.0.1576](https://ci.appveyor.com/project/az0/bleachbit/builds/31792598). This indicates the problem is not caused by UPX. Instead, UPX compression (the way it is normally done on BleachBit) seems to mask the problem.

```
2020-03-28 22:26:33 - WARNING - UPX disabled
2020-03-28 22:26:33 - INFO - Reduced size of the dist directory by 0 B from 35,754,491 B to 35,754,491 B in 0.0 s
2020-03-28 22:26:33 - INFO - Checking bleachbit_console.exe starts
C:\projects\bleachbit\dist\library.zip\win_unicode_console\__init__.py:31: RuntimeWarning: sys.stdin.encoding == 'utf-8', whereas sys.stdout.encoding == 'cp1252', readline hook consumer may assume they are the same
Traceback (most recent call last):
  File "bleachbit_console.py", line 47, in <module>
  File "C:\projects\bleachbit\bleachbit\__init__.py", line 286, in <module>
    from bleachbit import Windows
  File "C:\projects\bleachbit\bleachbit\Windows.py", line 41, in <module>
    from bleachbit import Command, FileUtilities, General
  File "C:\projects\bleachbit\bleachbit\Command.py", line 32, in <module>
    from sqlite3 import DatabaseError
  File "C:\Python34\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Python34\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
  File "<loader>", line 10, in <module>
  File "<loader>", line 8, in __load
ImportError: (DLL load failed: Invalid access to memory location.) 'C:\\projects\\bleachbit\\dist\\_sqlite3.pyd'

**Comment by mkhon** [comment]
> > But if I don't have upx/upx.exe (no UPX compression) the executable works properly
> 
> On which version of Windows?

Windows 10 x64

**Comment by ediowar** [comment]
> I recently did a test build with no UPX compression on any file

Where can I download portable version?

**Comment by az0** [comment]
> > I recently did a test build with no UPX compression on any file
> 
> Where can I download portable version?

Normally I would point you AppVeyor or ci.bleachbit.org, but that's where it failed to build. :)  Later when I have some time, I will see what I can do to provide a build

**Comment by mkhon** [comment]
@az0 I build with this patch:

```
diff --git a/windows/setup_py2exe.py b/windows/setup_py2exe.py
index a327c649..4e0310bb 100644
--- a/windows/setup_py2exe.py
+++ b/windows/setup_py2exe.py
@@ -413,7 +413,7 @@ def upx():
         return
 
     logger.info('Compressing executables')
-    upx_files = recursive_glob('dist', ['*.exe', '*.dll', '*.pyd'])
+    upx_files = recursive_glob('dist', ['*.dll', '*.pyd'])
     cmd = '{} {} {}'.format(UPX_EXE, UPX_OPTS, ' '.join(upx_files))
     run_cmd(cmd)
 ```

And bleachbit.exe and bleachbit_console.exe work fine for me.
UP 3.96, strip.exe from mingw
