### ISSUE TITLE
urlopen error unknown url type: https

### ISSUE THREAD

**Issue by az0** [bleachbit/bleachbit#849]
Windows 10 without Python environment/developer tools
BleachBit version 3.9.1
Build number 1612

Error message happens on startup
`Error when opening a network connection to check for updates. Please verify the network is working and that a firewall is not blocking this application. Error message: <urlopen error unknown url type: https>`

**Comment by az0** [comment]
When downloading files to make chaff, I also get these errors

````
Downloading https://sourceforge.net/projects/bleachbit/files/chaff/clinton_subject_model.json.bz2/download to C:\Users\x\AppData\Roaming\BleachBit\clinton_subject_model.json.bz2
Downloading url failed: https://sourceforge.net/projects/bleachbit/files/chaff/clinton_subject_model.json.bz2/download
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 588, in urlopen
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 248, in _get_conn
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 816, in _new_conn
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 449, in send
  File "C:\Python34\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
  File "C:\Python34\lib\site-packages\urllib3\util\retry.py", line 399, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sourceforge.net', port=443): Max retries exceeded with url: /projects/bleachbit/files/chaff/clinton_subject_model.json.bz2/download (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Chaff.py", line 143, in download_url_to_fn
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 546, in get
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 533, in request
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 646, in send
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='sourceforge.net', port=443): Max retries exceeded with url: /projects/bleachbit/files/chaff/clinton_subject_model.json.bz2/download (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))

````

**Comment by mkhon** [comment]
I can not reproduce on rather clean Windows machine (Windows 2008 Server) without Python environment/developer tools.

I tried builds 3.9.1.1612 and 3.9.1.1621.

**Comment by mkhon** [comment]
I tested with 3.9.1.1622 (portable) on Windows 10 x64 (more or less clean, almost no third-party software installed, no development tools installed at all), Windows 7 x86 (only Google Chrome installed) - can not reproduce.

**Comment by az0** [comment]
I also do not see it with 3.9.1.1622 portable on the same "clean" Windows 10 system.

**Comment by az0** [comment]
I don't see it after installing 1622 on the same system. Maybe it had to do with the virus ([false positive](https://github.com/bleachbit/bleachbit/issues/842)) I had on the same system, and that's resolved too.
