### ISSUE TITLE
3.9.2 Beta - Error: libreoffice.history - MX-18 (Debian 9)

### ISSUE THREAD

**Issue by v17564** [bleachbit/bleachbit#872]
Hi. I instaled the last beta from Debian package in your web page: bleachbit_3.9.2_all_debian9.deb

The Libreoffice i have instaled is:  6.0.1-1~bpo9+1 and I found this error in:

Error: libreoffice.history: Function: Limpiar: /home/username/.config/libreoffice/4/user/registrymodifications.xcu

Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 87, in execute for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 160, in execute self.func(self.path)
  File "/usr/share/bleachbit/Special.py", line 234, in delete_office_registrymodifications dom1 = xml.dom.minidom.parse(path)
  File "/usr/lib/python3.5/xml/dom/minidom.py", line 1958, in parse return expatbuilder.parse(file)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 911, in parse result = builder.parseFile(fp)
  File "/usr/lib/python3.5/xml/dom/expatbuilder.py", line 211, in parseFile parser.Parse("", True)
xml.parsers.expat.ExpatError: no element found: line 232, column 198

Thanks.

**Comment by v17564** [comment]
After two times executed the program the error was there but on having executed a third time the error disappeared. I don't know what happen but I close this entry. ???. Thanks.
