### ISSUE TITLE
UnicodeDecodeError while creating Google Chrome

### ISSUE THREAD

**Issue by Robert51** [bleachbit/bleachbit#874]
French Windows 10 64 bit.
Error red lines in the cleaning log:
Error: google_chrome.history: Function: Clean file: C:\Users\Administrateur\AppData\Local\Google\Chrome\User Data\Default\History
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 186, in delete_chrome_history
  File "C:\projects\bleachbit\bleachbit\Special.py", line 324, in get_chrome_bookmark_ids
  File "C:\projects\bleachbit\bleachbit\Special.py", line 338, in get_chrome_bookmark_urls
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 102157: character maps to <undefined>
…
Error: opera.history: Function: Clean file: C:\Users\Administrateur\AppData\Roaming\Opera Software\Opera Stable\History
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 186, in delete_chrome_history
  File "C:\projects\bleachbit\bleachbit\Special.py", line 324, in get_chrome_bookmark_ids
  File "C:\projects\bleachbit\bleachbit\Special.py", line 338, in get_chrome_bookmark_urls
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 101503: character maps to <undefined>
...
Diagnostics log:
BleachBit version 4.0.0
Build number 1628
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = True
SQLite version 3.31.1
local_cleaners_dir = None
locale_dir = C:\Users\Administrateur\AppData\Local\BleachBit\share\locale\
options_dir = C:\Users\Administrateur\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\Administrateur\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Users\Administrateur\AppData\Local\BleachBit\share\cleaners\
locale.getdefaultlocale = ('fr_FR', 'cp1252')
os.getenv('APPDATA') = C:\Users\Administrateur\AppData\Roaming
os.getenv('cd') = C:\Users\Administrateur\AppData\Local\BleachBit
os.getenv('LocalAppData') = C:\Users\Administrateur\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\Administrateur\AppData\LocalLow
os.getenv('Music') = C:\Users\Administrateur\Music
os.getenv('USERPROFILE') = C:\Users\Administrateur
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\ADMINI~1\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\Administrateur
platform.win32_ver[1]() = 10.0.18362
platform.platform = Windows-10-10.0.18362
platform.version = 10.0.18362
sys.argv = ['C:\\Users\\Administrateur\\AppData\\Local\\BleachBit\\bleachbit.exe', '--gui', '--no-uac']
sys.executable = C:\Users\Administrateur\AppData\Local\BleachBit\bleachbit.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Users\Administrateur\AppData\Local\BleachBit\library.zip\bleachbit\Diagnostic.pyo

**Comment by az0** [comment]
I have not looked into it, but I am guessing BleachBit should be forced to read these Google Chrome files in utf-8 encoding instead of the system cp1252 encoding.

**Comment by az0** [comment]
@Robert51 
Thank you for the good bug report. You were first, but this turned out to be a common issue. Max coded a fix, and I merged it. When you get a chance, would you please download version 4.0.1.1660 or newer from https://ci.bleachbit.org/ and test it? It should be there in ~15 minutes.

**Comment by az0** [comment]
FYI, there is a digitally-signed Windows installer with this fix available via the [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta) page
