### ISSUE TITLE
UnicodeDecodeError on chrome history cleaning, v 4.0.0.

### ISSUE THREAD

**Issue by troette** [bleachbit/bleachbit#877]
Hi

Running 4.0.0 upgraded from 3.2.0 on Windows 1909 with standard settings of

Fehler: google_chrome.history: Function: Datei bereinigen: C:\Users\gyroplane\AppData\Local\Google\Chrome\User Data\Default\History
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 186, in delete_chrome_history
  File "C:\projects\bleachbit\bleachbit\Special.py", line 324, in get_chrome_bookmark_ids
  File "C:\projects\bleachbit\bleachbit\Special.py", line 338, in get_chrome_bookmark_urls
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 10644: character maps to <undefined>

![bleachbit](https://user-images.githubusercontent.com/27011629/79719491-fa2fab00-82de-11ea-8dbf-fd54be762b2b.PNG)

**Comment by az0** [comment]
Thank you for the report, @troette . I'll look into it.

Your Windows system is set to German, right?

**Comment by troette** [comment]
Hi Andrew

Thanks for your replay. my keyboard Swissgerman:

BleachBit version 4.0.0
Build number 1628
locale.getdefaultlocale = ('de_CH', 'cp1252')

------ Originalnachricht ------
Von: "Andrew Ziem" <notifications@github.com>
An: "bleachbit/bleachbit" <bleachbit@noreply.github.com>
Cc: "troette" <quandolf@gmail.com>; "Mention" 
<mention@noreply.github.com>
Gesendet: 20.04.2020 16:18:20
Betreff: Re: [bleachbit/bleachbit] Error on chrome history cleaning, v 
4.0.0. (#877)

**Comment by GrepSecurity** [comment]
@az0 , do you have any update on this issue? I am facing the same error, also, the Chrome History wasn't cleared.

Running on 4.0.0

**Comment by fridaycarrot** [comment]
Hi, I have the same issue, using english:

Error: google_chrome.history: Function: Clean file: C:\Users\xxxxx\AppData\Local\Google\Chrome\User Data\Default\History
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 186, in delete_chrome_history
  File "C:\projects\bleachbit\bleachbit\Special.py", line 324, in get_chrome_bookmark_ids
  File "C:\projects\bleachbit\bleachbit\Special.py", line 338, in get_chrome_bookmark_urls
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 16499: character maps to <undefined>

**Comment by Surfride10** [comment]
bb 4.0.0 confirming Chrome Version 83.0.4103.61 (Official Build) (64-bit) chrome history is not cleanup, doing it manually...

**Comment by mkhon** [comment]
Fixed in #951

**Comment by az0** [comment]
@troette 
@GrepSecurity 
@fridaycarrot 
@Surfride10 
When you get a chance, would you please download version 4.0.1.1660 or newer from https://ci.bleachbit.org/ and test it? It should be there in ~15 minutes. Afterwards, you should not have have the UnicodeDecodeError when cleaning Google Chrome.

If you do *not* see this error but Chrome history is still not cleaned, let's file a new issue. This issue is about the UnicodeDecodeError for Chrome history.

**Comment by mkhon** [comment]
@az0 I think this one can be marked as fixed as dup of #890 or #938

**Comment by az0** [comment]
@troette
@GrepSecurity
@fridaycarrot
@Surfride10

If you have the same `UnicodeDecodeError` when cleaning Google Chrome history, re-open this issue.
