### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_iter'

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#881]
[bleachbit_4.0.0_all_ubuntu1604.deb](https://www.bleachbit.org/download/file/t?file=bleachbit_4.0.0_all_ubuntu1604.deb)
`sudo bleachbit`
The menu option "Shred Settings and Quit"
```
clean_operation('_gui'), options = '['files']'
elapsed time: 0 seconds
Deleting configuration: /home/dzmitry/.config/bleachbit/bleachbit.ini 
Automatically preserving language en.
clean_operation('_gui'), options = '['files']'
Exception while running operation '_gui': ''NoneType' object has no attribute 'get_iter''
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 353, in run_operations
    for dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/Worker.py", line 174, in clean_operation
    self.ui.update_item_size(operation, option_id, self.size)
  File "/usr/share/bleachbit/GUI.py", line 915, in update_item_size
    __iter = model.get_iter(treepath)
AttributeError: 'NoneType' object has no attribute 'get_iter'

(bleachbit:4991): Gtk-CRITICAL **: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed
elapsed time: 0 seconds

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit:4991): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed
```

**Comment by mkhon** [comment]
@ediowar can you provide the output of "lsb_release -a"?

**Comment by mkhon** [comment]
This was broken in this commit: 1305cb279ae50d4dfc0428092a10e6910b63861e

The reason is that quit (called after idle_add) is called prior to calling cleaner (which after this commit is also added with Glib.PRIORITY_LOW).

**Comment by ediowar** [comment]
Sometimes messages remain
```
(bleachbit.py:3072): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit.py:3072): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit.py:3072): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed
``

**Comment by az0** [comment]
Looks good on Windows 10 and Ubuntu 20.04

**Comment by ediowar** [comment]
### Steps to Reproduce

1. Run BB
2. Check the "Show debug messages" checkbox in the settings
3. Close BB
4. Run BB
5. Shred Settings and Quit

**Comment by mkhon** [comment]
This one was re-opened because PR #955 did not contain the fix from PR #953
Should be marked as resolved back.

**Comment by ediowar** [comment]
The above messages still appear.

**Comment by ediowar** [comment]
Messages still appear. When running BB with sudo
```
(bleachbit.py:5238): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit.py:5238): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit.py:5238): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed
```
And when running BB without sudo
```
(bleachbit.py:5109): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed

(bleachbit.py:5109): Gtk-CRITICAL **: gtk_text_view_scroll_mark_onscreen: assertion 'get_buffer (text_view) == gtk_text_mark_get_buffer (mark)' failed
```
In addition, after BB session with sudo, issue https://github.com/bleachbit/bleachbit/issues/964 occurs when starting BB without sudo

**Comment by mkhon** [comment]
@ediowar this bug and fix was for AttributeError when Shred Settings and Quit is used.

The messages you see when running under sudo are a different bug
