### ISSUE TITLE
Strange red error entries in the log file (UnicodeDecodeError for Chrome and Opera)

### ISSUE THREAD

**Issue by Robert51** [bleachbit/bleachbit#933]
I managed to make Bleachbit launch and work on my Windows 10 64 bit system (build 4.0.1.1643). But the log file always includes the following red lines:
Error: opera.history: Function: Clean file: C:\Users\Admin\AppData\Roaming\Opera Software\Opera Stable\History

Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 186, in delete_chrome_history
  File "C:\projects\bleachbit\bleachbit\Special.py", line 324, in get_chrome_bookmark_ids
  File "C:\projects\bleachbit\bleachbit\Special.py", line 338, in get_chrome_bookmark_urls
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 101503: character maps to <undefined>

Error: google_chrome.history: Function: Clean file: C:\Users\Admin\AppData\Local\Google\Chrome\User Data\Default\History
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 186, in delete_chrome_history
  File "C:\projects\bleachbit\bleachbit\Special.py", line 324, in get_chrome_bookmark_ids
  File "C:\projects\bleachbit\bleachbit\Special.py", line 338, in get_chrome_bookmark_urls
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 102157: character maps to <undefined>

The problem is that I have no “C:\projects\bleachbit\bleachbit” folder on my system!

**Comment by az0** [comment]
The systems here look like issue https://github.com/bleachbit/bleachbit/issues/877 . 

It is normal that you do not have the path `C:\projects\bleachbit\bleachbit`. This path refers to the environment on which BleachBit was built. 

Would you please let me know the language of your system? It's shown in BleachBit under diagnostics. Specifically, please find the line that looks like `locale.getdefaultlocale = ('en_US', 'UTF-8')` and paste it here.

**Comment by Robert51** [comment]
BleachBit version 4.0.1
Build number 1643
GTK version 3.18.9
locale.getdefaultlocale = ('fr_FR', 'cp1252')

**Comment by mkhon** [comment]
Fixed in #951

**Comment by az0** [comment]
@Robert51 
When you get a chance, would you please download version 4.0.1.1660 or newer from https://ci.bleachbit.org/ and test it? It should be there in ~15 minutes. Afterwards, you should not have have the UnicodeDecodeError when cleaning the history of Google Chrome or Opera.

**Comment by bgolding99** [comment]
I am having similar problems on my Windows 10 system but with even more errors:

Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\PC\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/host_referral_list 
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 244, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 263, in clean_json
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13713: character maps to <undefined>
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\PC\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=dns_prefetching/startup_list 
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 244, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 263, in clean_json
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13713: character maps to <undefined>
Error: google_chrome.cache: Command to clean JSON file, path=C:\Users\PC\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=net/http_server_properties/servers 
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 244, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 263, in clean_json
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13713: character maps to <undefined>

and

Error: google_chrome.history: Command to clean JSON file, path=C:\Users\PC\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=profile/content_settings/exceptions 
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 244, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 263, in clean_json
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13713: character maps to <undefined>

and 

Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\PC\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=account_info 
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 244, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 263, in clean_json
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13713: character maps to <undefined>
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\PC\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=google_services 
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 244, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 263, in clean_json
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 13713: character maps to <undefined>
Error: google_chrome.sync: Command to clean JSON file, path=C:\Users\PC\AppData\Local\Google\Chrome\User Data\Default\Preferences, address=sync 

I did not have Google Chrome open at the time and there was no chrome.exe process running in Task Manager.

This is my BleachBit system information:

BleachBit version 4.0.0
Build number 1628
GTK version 3.18.9
locale.getdefaultlocale = ('en_US', 'cp1252')

I tried installing version 4.0.1.1668 as directed above but was unable to do so even after clicking through "More info" on the Windows Defender SmartScreen pop-up.

Any help would be appreciated.
Thanks!

P.S. I am a casual user and not a developer.

**Comment by Robert51** [comment]
BleachBit-4.0.1.1662-setup-English.exe installed normally and is working correctly on Windows 10 Home 64 bit.

**Comment by az0** [comment]
> is working correctly on Windows 10 Home 64 bit.

@Robert51 
Thank you for testing. I will close the issue.

> I tried installing version 4.0.1.1668 as directed above but was unable to do so even after clicking through "More info" on the Windows Defender SmartScreen pop-up.

@bgolding99 
This error will continue to happen in BleachBit version 4.0.0 unless you disable the history option for Google Chrome, Opera, and Chromium.

In case it helps, here is a YouTube video about [how to get past the SmartScreen warning to install BleachBit ](https://www.youtube.com/watch?v=Uk3f8mBYY08)(at least, in a normal case). 

Another option is waiting for the next beta or final release. These don't have the SmartScreen warning (except maybe the first day or so after the release).
