### ISSUE TITLE
Free Disk Space Failing

### ISSUE THREAD

**Issue by Surfride10** [bleachbit/bleachbit#934]
Windows Server 2012r2
BB version 4.0.0 System:Free Disk Space fails with:

Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.Error: system.free_disk_space: Function: Overwrite free disk space C:\
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 145, in execute
  File "C:\projects\bleachbit\bleachbit\Cleaner.py", line 569, in wipe_path_func
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 917, in wipe_path
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 871, in temporaryfile
  File "C:\Python34\lib\tempfile.py", line 484, in NamedTemporaryFile
  File "C:\Python34\lib\tempfile.py", line 207, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'C:\\tmp38c031ew5jVJEvNunCZi_4nOS0KHFaLAmZ3bcKReNOr9yJlMzAlk7CVxYif8gK84zQTt0yGhVNzYV8NImEI4PHXAFMprDU3WCAD-e0tjH1DAPe7LedDLWeaREgHTOY115CVJ02EF4YEcStk8_Yand9wpPSjkpA5TBmhW89pZ0XD-YAftU2TqQLGJGmwMPcA0CvHtsSIqVNgufPQHEoL07MT7dKsXmyBvXnCUTDZYmZQY3wodw1NjtZUvm-SEa'
Error: system.free_disk_space: Function: Overwrite free disk space D:\
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 145, in execute
  File "C:\projects\bleachbit\bleachbit\Cleaner.py", line 569, in wipe_path_func
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 917, in wipe_path
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 871, in temporaryfile
  File "C:\Python34\lib\tempfile.py", line 484, in NamedTemporaryFile
  File "C:\Python34\lib\tempfile.py", line 207, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'D:\\tmp08wljtukSWXag-7l7uvF-nonqvW0OTWdxLHkefcgvdwocKi4k5MUBJjrrM2JoH4sZxiH1bbn.kYifsPBW_ReLj6WXtfS_.HW-t0CkE89yYoLtgeWUZxwM8b0dDyzyMt8bGyk_rfhUzImx-0vd8jlXbpuCA2GkiNy9L.xGauq68dBRY0hXALl1NOeOSzX0KuCMujYf.LNHSoSsA.YxNnGYTRmpZW2eNKITgd01-37MuICTkVBqjQJPuoRM2pAn'
	

Thanks!

~David

**Comment by az0** [comment]
Thank you for the report. This is a bug in BleachBit 4.0.0. It's like issue https://github.com/bleachbit/bleachbit/issues/899 . For now, one workaround is to downgrade to BleachBit 3.2.0. When a fix is ready, I'll post a message here to ask you to try it out

**Comment by mkhon** [comment]
Fixed by #957

**Comment by Surfride10** [comment]
I tested 4.0.1.1671, ff is cleaning properly, chrome history is gone, but
the cookies are not being erased.

thanks for looking into this, appreciate what you do

~David

**Comment by az0** [comment]
> I tested 4.0.1.1671, ff is cleaning properly, chrome history is gone

I take it you did not get a similar error like `OSError: [Errno 22] Invalid argument: 'D:\tmp08wljtukSWXag-7l` when wiping free space, so I will close this issue.

> but the cookies are not being erased. 

If cookies are not being erased, please open a new issue. Please clearly indicate the type of browser, version of browser, and the steps to reproduce the issue. For example, did you check the cookies in the browser's settings? Or did you visit a web page, and it remembered your login?

>thanks for looking into this, appreciate what you do
You're welcome
