### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#964]
Ubuntu 16.04, git revision https://github.com/bleachbit/bleachbit/commit/7fbcf094f508274021eb97647d7e82e41c29f430
```
~/Downloads/bleachbit-master$ python3 bleachbit.py
Traceback (most recent call last):
  File "bleachbit.py", line 43, in <module>
    import bleachbit.GUI
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/GUI.py", line 26, in <module>
    from bleachbit import Cleaner, FileUtilities
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Cleaner.py", line 32, in <module>
    from bleachbit.Options import options
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Options.py", line 381, in <module>
    options = Options()
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Options.py", line 97, in __init__
    self.restore()
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Options.py", line 300, in restore
    self.set("version", bleachbit.APP_VERSION)
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Options.py", line 306, in set
    self.__flush()
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Options.py", line 106, in __flush
    with open(bleachbit.options_file, 'w', encoding='utf-8-sig') as _file:
PermissionError: [Errno 13] Permission denied: '/home/dzmitry/.config/bleachbit/bleachbit.ini'
```

**Comment by ediowar** [comment]
I deleted /home/dzmitry/.config/bleachbit/bleachbit.ini, the error is gone.
