### ISSUE TITLE
bleach bit issue - google chrome history cleaning error

### ISSUE THREAD

**Issue by jwlohrman** [bleachbit/bleachbit#966]
Using Bleachbit 4.0.0 on Windows 8.1

Error Message below
;
Error: google_chrome.history: Function: Clean file: C:\Users\Joe\AppData\Local\Google\Chrome\User Data\Default\History
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 160, in execute
  File "C:\projects\bleachbit\bleachbit\Special.py", line 186, in delete_chrome_history
  File "C:\projects\bleachbit\bleachbit\Special.py", line 324, in get_chrome_bookmark_ids
  File "C:\projects\bleachbit\bleachbit\Special.py", line 338, in get_chrome_bookmark_urls
  File "C:\Python34\lib\json\__init__.py", line 265, in load
  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 180869: character maps to <undefined>
;
ran all options of chrome cleaning and received this error; unchecked all areas except history cleaning and  got same error

**Comment by mkhon** [comment]
Dup of #874 (already fixed)

**Comment by jwlohrman** [comment]
Thank you... will update version of bleachbit.

**Comment by jwlohrman** [comment]
Thanks
