### ISSUE TITLE
BB don't wipe free space

### ISSUE THREAD

**Issue by CatalinFrance** [bleachbit/bleachbit#987]
Here's the message:

Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.Error: _gui.free_disk_space: Function: Overwrite free disk space C:\
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 145, in execute
  File "C:\projects\bleachbit\bleachbit\Cleaner.py", line 744, in wipe_path_func
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 917, in wipe_path
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 871, in temporaryfile
  File "C:\Python34\lib\tempfile.py", line 484, in NamedTemporaryFile
  File "C:\Python34\lib\tempfile.py", line 207, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'C:\\tmpj3t2blu8lKipPu8QWxS6u7-ohuG8EJ3ua6iFy-ZK1k9Up9VwSrgVerbE4qaIFPiFOLIsh62WzlBunj3yOce.f68VfkJ3-AtSbvd3HHaKSHKz_s5QPoVemcwCxxhEdBZdlBJbv.A1H2keTwYEU0p.S.hHnjuRb5i7ET9QM5Oh5VNM6SrImkmNXwT_6U7NwMO_kfYh9r0mDth1cnClZto5QXNHt1FPT9uGx3GeY6Q3f4p02Ie3x0_i.YDP0QXbu'

Disk space recovered: 0
Files deleted: 0
Errors: 1

What's wrong?...
Best wishes, Catalin C.  France

**Comment by ediowar** [comment]
https://www.bleachbit.org/news/bleachbit-400#known_issues
