### ISSUE TITLE
RuntimeError: swapoff: /dev/sda7: swapoff failed: Cannot allocate memory

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#996]
Running from source code, git revision https://github.com/bleachbit/bleachbit/commit/f63876353ade695d8e19969439bb5040daf3d4f6
Ubuntu 16.04
```
clean_operation('system'), options = '[]'
running cmd swapon -s
Disabling swap.
running cmd swapoff -a -v
Error: system.memory: Function: Memory
Traceback (most recent call last):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Worker.py", line 87, in execute
    for ret in cmd.execute(self.really_delete):
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Command.py", line 145, in execute
    for func_ret in self.func():
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Memory.py", line 306, in wipe_memory
    devices = disable_swap_linux()
  File "/home/dzmitry/Downloads/bleachbit-master/bleachbit/Memory.py", line 82, in disable_swap_linux
    raise RuntimeError(stderr.replace("\n", ""))
RuntimeError: swapoff: /dev/sda7: swapoff failed: Cannot allocate memory

Disk space recovered: 0
Files deleted: 0
Errors: 1
elapsed time: 0 seconds
```
```
BleachBit version 4.0.1
GTK version 3.18.9
GTK theme = Ambiance
GTK icon theme = ubuntu-mono-dark
GTK prefer dark theme = True
SQLite version 3.11.0
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /home/dzmitry/.config/bleachbit
personal_cleaners_dir = /home/dzmitry/.config/bleachbit/cleaners
system_cleaners_dir = /home/dzmitry/Downloads/bleachbit-master/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = None
os.getenv('LOGNAME') = root
os.getenv('USER') = root
os.getenv('SUDO_UID') = 1000
os.path.expanduser('~') = /home/dzmitry
platform.linux_distribution() = ('Ubuntu', '16.04', 'xenial')
platform.platform = Linux-4.15.0-110-generic-x86_64-with-Ubuntu-16.04-xenial
platform.version = #111~16.04.1-Ubuntu SMP Mon Jul 6 15:52:27 UTC 2020
sys.argv = ['bleachbit.py']
sys.executable = /usr/bin/python3
sys.version = 3.5.2 (default, Jul 17 2020, 14:04:10) 
[GCC 5.4.0 20160609]
__file__ = /home/dzmitry/Downloads/bleachbit-master/bleachbit/Diagnostic.py
```
![Screenshot from 2020-08-29 19-59-08](https://user-images.githubusercontent.com/44164186/91642532-be4ae600-ea34-11ea-8a9f-0197316f0bd9.png)

**Comment by az0** [comment]
The memory cleaning function temporarily disables the swap file, but on this system, there is not RAM to disable the swap. (The screenshot shows the memory is 95% full, and the swap is 46% full.) There's not much BleachBit can do except give a friendly error message. Would that help?

**Comment by ediowar** [comment]
Is there no way to disable the swap without RAM?

**Comment by az0** [comment]
It is possible to disable swap only if there is enough RAM to hold 100% the allocated memory. In the screenshot, 3.5 GiB+1.8GiB was allocated, but that wouldn't fit into the 3.7 GiB of RAM installed. Another option is to close memory-hungry programs---maybe Google Chrome.
